### PR TITLE
fix #11033

### LINKED ISSUE #11033: dubbo token 消费者无法获取并传递到服务提供者，其他主动添加的隐式参数也无法传递到服务提供者
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.0
* Operating System version: windows10
* Java version: 11

### Steps to reproduce this issue
希望使用dubbo token 来鉴权
1. 在服务提供者的实现注解上开启token
```
@DubboService(protocol = "rest", validation = "true", token = "true")
public class AdMaterialController implements AdMaterialControllerI_Test {
    @Autowired
    private AdMaterialQueryService adMaterialQueryService;
    @Override
    public AdResponse edit(AdMaterialEdit req) {
        AdResponse<AdMaterialDto> resp = adMaterialQueryService.edit(req);
        return resp;
    }

}
```
2.查看nacos，元数据中有token

### Expected Behavior

Screenshot_121
remoteToken为Null

后续 主动主动向RpcContext上下文中添加隐式参数，跟踪发现走的是
org.apache.dubbo.rpc.proxy.AbstractProxyInvoker 调用时根本没有使用隐式参数
```
Object value = doInvoke(proxy, invocation.getMethodName(), invocation.getParameterTypes(), invocation.getArguments());
```

### PR DESCRIPTION
**Pull request by ShenFeng312**
## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by ShenFeng312** [comment]
目前 已dubbo 的参数做参照传递  看了下GRPC  也是调用org.apache.dubbo.rpc.protocol.AbstractInvoker#AbstractInvoker(java.lang.Class<T>, org.apache.dubbo.common.URL)这个方法 可能也有相同情况

File: dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyInvoker.java [hunk 1]
```diff
@@ -97,6 +99,11 @@ public Result invoke(Invocation invocation) throws RpcException {
                 }
             }
 
+            Map<String, String> invocationAttachments = invocation.getAttachments();
+            if (CollectionUtils.isNotEmptyMap(invocationAttachments)) {
+                RpcContext.getClientAttachment().getObjectAttachments().putAll(invocationAttachments);
+            }
+
```
Comment (AlbumenJ) [inline dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyInvoker.java:106]: It would be better to replace the way to get attachment in customized filter of rest protocol to  `org.apache.dubbo.rpc.RpcServiceContext#getInvocation` to get the origin invocation.

File: dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java [hunk 2]
```diff
@@ -125,7 +126,11 @@ public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcExcept
         }
 
         if (invocation instanceof RpcInvocation) {
-            ((RpcInvocation) invocation).setInvoker(invoker);
+            RpcInvocation rpcInvocation = (RpcInvocation) invocation;
+            rpcInvocation.setInvoker(invoker);
+            //write all attachments back;
+            rpcInvocation.getObjectAttachments().putAll(context.getObjectAttachments());
+
```
Comment (AlbumenJ) [inline dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java:133]: It would be better to fill in the attachment when creating rpcInvocation, so as to avoid the performance loss caused by multiple coverage. If it is to pass information from the rest filter, you can extend a field in RpcServiceContext, obtain it in AbstractProxyInvoker and use it when creating a new invocation.

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

File: dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyInvoker.java (hunk 1 above)
Comment (wxbty) [reply dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyInvoker.java:106]: Why does the AbstractProxyInvoker on the provider side use ClientAttachment?

**Review by AlbumenJ — APPROVED** [review]
LGTM

**Review by AlbumenJ — CHANGES_REQUESTED** [review]
Please fix the conflicts with `3.2` branch.
The changes may break users. So, I think we should merge it into `3.2` branch.

**Comment by ShenFeng312** [comment]
> Please fix the conflicts with `3.2` branch. The changes may break users. So, I think we should merge it into `3.2` branch.

所以需要我把我的commit改都3.2分支吗  不好意思前几天新冠比较严重没有看到

**Comment by ShenFeng312** [comment]
There are still some errors, but I don't know how to solve them

**Comment by AlbumenJ** [comment]
> There are still some errors, but I don't know how to solve them

They are not cause by this PR. I will merge this PR later. Thanks for your contribution.

**Comment by AlbumenJ** [comment]
@ShenFeng312 Would you please add some integration test cases in apache/dubbo-samples to verify this PR?

**Comment by ShenFeng312** [comment]
> @ShenFeng312 Would you please add some integration test cases in apache/dubbo-samples to verify this PR?

done  https://github.com/apache/dubbo-samples/pull/698
