### PR TITLE
[Dubbo-4793]make RegistryDirectory can refresh the invokers when providers number become 0 when using nacos registry

### LINKED ISSUE #4793: dubbo+nacos服务发现bug
### Environment

* Dubbo version: 2.7.3 + nacos 1.1.0
* Operating System version: linux/mac
* Java version: 1.8

### Steps to reproduce this issue

1. 根据[文档](http://dubbo.apache.org/zh-cn/docs/user/configuration/api.html)通过代码使用dubbo
2. 在机器X启动A服务provider
3. 在机器X启动consumerA1，timeout参数为3000，目标是服务A
4. 在step3的同一进程启动consumerA2，timeout参数为8000，目标也是服务A
5. 下线机器X的A服务provider，上线机器Y的A服务provider
6. 通过consumerA2调用服务A还是去已近下线的机器X的A服务provider，连不通，即没有感知到服务上下线，没有去连机器Y的服务Aprovider

debug调试源码发现是`NacosRegistry`的`subscribeEventListener`会校验serviceName，同一serviceName只能往NamingService/EventDispatcher注册订阅一个lisnter(consumer)，虽然EventDispatcher本身可以一个key加多个listener，看看NacosRegistry是不是这块是不是有bug

```java 
//NacosRegistry.java
    private void subscribeEventListener(String serviceName, final URL url, final NotifyListener listener)
            throws NacosException {
        if (!nacosListeners.containsKey(serviceName)) {
            EventListener eventListener = event -> {
                if (event instanceof NamingEvent) {
                    NamingEvent e = (NamingEvent) event;
                    notifySubscriber(url, listener, e.getInstances());
                }
            };
            namingService.subscribe(serviceName, eventListener);
            nacosListeners.put(serviceName, eventListener);
        }
    }
```

``` java 
//EventDispatcher.java
    public void addListener(ServiceInfo serviceInfo, String clusters, EventListener listener) {

        NAMING_LOGGER.info("[LISTENER] adding " + serviceInfo.getName() + " with " + clusters + " to listener map");
        List<EventListener> observers = Collections.synchronizedList(new ArrayList<EventListener>());
        observers.add(listener);

        observers = observerMap.putIfAbsent(ServiceInfo.getKey(serviceInfo.getName(), clusters), observers);
        if (observers != null) {
            observers.add(listener);
        }

        serviceChanged(serviceInfo);
    }
```

### Expected Result

consumerA2可以连接到正确机器Y的A服务provider

### Actual Result

consumerA2可以连接到下线机器X的A服务provider

### PR DESCRIPTION
**Pull request by tswstarplanet**
## What is the purpose of the change

fix #4793

## Brief changelog

NacosRegistry.java

fix issue 4793, add toUrlWithEmpty emthod like ZookeeperRegistry.java, when the provider number become 0, generate an url with empty protocol.

## Verifying this change

has been test

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

File: dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java [hunk 1]
```diff
@@ -369,15 +370,26 @@ private void filterServiceNames(Set<String> serviceNames, URL url) {
...
+        return urls;
+    }
+
+    private List<URL> buildURLs(URL consumerURL, Collection<Instance> instances) {
         List<URL> urls = new LinkedList<>();
-        for (Instance instance : instances) {
-            URL url = buildURL(instance);
-            if (UrlUtils.isMatch(consumerURL, url)) {
-                urls.add(url);
+        if (instances != null && !instances.isEmpty()) {
```
Comment (Moriadry) [inline dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java]: Maybe we don't  need to check whether `instances` is empty

File: dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java [hunk 2]
```diff
@@ -406,9 +418,11 @@ private void subscribeEventListener(String serviceName, final URL url, final Not
      */
     private void notifySubscriber(URL url, NotifyListener listener, Collection<Instance> instances) {
         List<Instance> healthyInstances = new LinkedList<>(instances);
-        // Healthy Instances
-        filterHealthyInstances(healthyInstances);
-        List<URL> urls = buildURLs(url, healthyInstances);
+        if (healthyInstances.size() > 0) {
```
Comment (Moriadry) [inline dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java]: If healthyInstances is empty, this still works? Not sure, could u pls check it.
I believe we should make our code as clean as possible :)

File: dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java [hunk 3]
```diff
@@ -369,15 +370,26 @@ private void filterServiceNames(Set<String> serviceNames, URL url) {
         return serviceNames;
     }
 
-    private List<URL> buildURLs(URL consumerURL, Collection<Instance> instances) {
-        if (instances.isEmpty()) {
-            return Collections.emptyList();
+    private List<URL> toUrlWithEmpty(URL consumerURL, Collection<Instance> instances) {
```
Comment (Moriadry) [inline dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java]: Last nitpick, what about changing  `toUrlWithEmpty` to  `toUrlsWhenEmpty`? (a suggestion, there should be another better method name to make it clear)

I know we use `toUrlWithEmpty` in zookeeperRegistry.class, but I found the name may bring us a little confusion :)

File: dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java (hunk 1 above)
Comment (tswstarplanet) [reply dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java]: For String or Collection, I think not only null, but also size check are needed because the for each will create useless iterator object.

File: dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java (hunk 2 above)
Comment (tswstarplanet) [reply dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java]: Same as above.

File: dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java (hunk 3 above)
Comment (tswstarplanet) [reply dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java]: The name tells that the protocol will be set "empty"
