### PR TITLE
[Dubbo]Fix: Collections.emptyList() is final

### LINKED ISSUE #14895: [Bug] org.apache.dubbo.remoting.http12.message.DefaultHttpRequest locales()
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo java 3.3.2
jdk 21
windows idea

### Steps to reproduce this issue

@Override
    public List<Locale> locales() {
        List<Locale> locales = this.locales;
        if (locales == null) {
            locales = HttpUtils.parseAcceptLanguage(headers.getFirst(HttpHeaderNames.CONTENT_LANGUAGE.getKey()));
            if (locales.isEmpty()) {
                locales.add(Locale.getDefault());
            }
            this.locales = locales;
        }
        return locales;
    }
public static List<Locale> parseAcceptLanguage(String header) {
        List<Item<Locale>> locales = new ArrayList<>();
        if (header == null) {
            return Collections.emptyList();
        }
        for (String item : StringUtils.tokenize(header, ',')) {
            String[] pair = StringUtils.tokenize(item, ';');
            locales.add(new Item<>(parseLocale(pair[0]), pair.length > 1 ? Float.parseFloat(pair[1]) : 1.0F));
        }
        return Item.sortAndGet(locales);
    }

Collections.emptyList() is final 

if Collections.emptyList()
 locales.add(Locale.getDefault()) throw exception

### What you expected to happen

no exception

### Anything else

_No response_

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by paradiseidler**
## What is the purpose of the change?
Fix #14895 What the Collections.emptyList( ) return is final.

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Make sure gitHub actions can pass. [Why the workflow is failing and how to fix it?](./CONTRIBUTING.md)

### CODE REVIEW

File: dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/HttpUtils.java [hunk 1]
```diff
@@ -126,7 +126,7 @@ public static float parseQuality(String expr, int index) {
     public static List<Locale> parseAcceptLanguage(String header) {
         List<Item<Locale>> locales = new ArrayList<>();
```
Comment (oxsean) [inline dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/HttpUtils.java:127]: Can you move this line to line 131? This will avoid creating unnecessary object.

File: dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/HttpUtils.java [hunk 2]
```diff
@@ -138,7 +138,7 @@ public static List<Locale> parseAcceptLanguage(String header) {
     public static List<Locale> parseContentLanguage(String header) {
         List<Locale> locales = new ArrayList<>();
         if (header == null) {
```
Comment (oxsean) [inline dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/HttpUtils.java:140]: Can you move this line to line 143? This will avoid creating unnecessary objects

File: dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/HttpUtils.java (hunk 1 above)
Comment (paradiseidler) [reply dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/HttpUtils.java:127]: OK

File: dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/HttpUtils.java (hunk 2 above)
Comment (paradiseidler) [reply dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/HttpUtils.java:140]: OK
