### PR TITLE
[master] fix NPE in doOverrideIfNecessary

### LINKED ISSUE #8765: RegistryProtocol的doOverrideIfNecessary方法里exporter.getInvoker()在实际应用场景下会不会是null
### Environment
master分支github构建日志显示ReferenceConfigTest测试方法testReferenceRetry() line 135出现NPE，
```
        try {
            System.setProperty("java.net.preferIPv4Stack", "true");
            sc.export();  // line 135:  NPE occurred here !!!
            demoService = rc.get();
            success = true;
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
```
在RegistryProtocol.doOverrideIfNecessary() 691行设置断点：
```
URL currentUrl = exporter.getInvoker().getUrl();
```
跟踪testReferenceRetry测试方法发现exporter.getInvoker()返回为null，提交了一个修复PR #8683 （for master）， #8768 （for 3.0），这个异常不会影响测试执行流程，因为调用方法FailbackRegistry.notify()捕获异常后只是输出error日志。

当前3.0分支ReferenceConfigTest测试方法testReferenceRetry() 改用InjvmProtocol.getInjvmProtocol().export(...)，不会再调用RegistryProtocol了，所以虽然3.0的RegistryProtocol取currentUrl的方法和master相同，都是exporter.getInvoker().getUrl()，但构建日志里并不会出现这个NPE。

不清楚实际应用场景下是否有master分支的这个测试场景， 这个问题有必要做修复么？

### PR DESCRIPTION
**Pull request by zrlw**
## What is the purpose of the change
fix #8765 on master

### CODE REVIEW

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java [hunk 1]
```diff
@@ -700,7 +700,7 @@ public synchronized void doOverrideIfNecessary() {
             newUrl = getConfiguredInvokerUrl(providerConfigurationListener.getConfigurators(), newUrl);
             newUrl = getConfiguredInvokerUrl(serviceConfigurationListeners.get(originUrl.getServiceKey())
                     .getConfigurators(), newUrl);
-            if (!currentUrl.equals(newUrl)) {
+            if (!newUrl.equals(currentUrl)) {
```
Comment (changfubai) [inline dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java:703]: 感觉可以抽一个工具类出来，判断两个url是否相同，这样就不用关注谁在前面谁在后面了

**Review by changfubai — APPROVED** [review]
LGTM

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java (hunk 1 above)
Comment (BurningCN) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java:703]: Objects.equals

Comment (zrlw) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java:703]: the newUrl could not be null, otherwise the function of doOverrideIfNecessary will be corrupted totally.
