### PR TITLE
fix #7315 redundant box for boolean and refactor method filterInvoker

### LINKED ISSUE #7315: Redundant box for boolean
- [ √] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ √] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: macos 10.14.6
* Java version: oracle 1.8.0_211

### Steps to reproduce this issue
1. method info 
org.apache.dubbo.rpc.cluster.router.tag.TagRouter#isForceUseTag
2. a boolean value is boxed  while a unboxed value is expected

### Expected Result

none box for boolean

### Actual Result

Redundant box for boolean

### others
Is the method graceful enough? org.apache.dubbo.rpc.cluster.router.tag.TagRouter#filterInvoker

### PR DESCRIPTION
**Pull request by 24kpure**
#7315

## What is the purpose of the change
unboxing boolean and refactor method filterInvoker

## Brief changelog
1.org.apache.dubbo.rpc.cluster.router.tag.TagRouter#isForceUseTag 
Boolean.valueOf -> Boolean.parseBoolean
2.org.apache.dubbo.rpc.cluster.router.tag.TagRouter#filterInvoker
refactor in stream
3.org.apache.dubbo.rpc.cluster.router.tag.TagRouter#filterUsingStaticTag
remove param(result) initial  value

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

File: dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouter.java [hunk 1]
```diff
@@ -160,7 +160,7 @@ public URL getUrl() {
      * @return
      */
     private <T> List<Invoker<T>> filterUsingStaticTag(List<Invoker<T>> invokers, URL url, Invocation invocation) {
-        List<Invoker<T>> result = invokers;
+        List<Invoker<T>> result;
```
Comment (chickenlj) [inline dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouter.java:163]: Why remove this assignment?

**Review by chickenlj — CHANGES_REQUESTED** [review]

File: dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouter.java (hunk 1 above)
Comment (chickenlj) [reply dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouter.java:163]: Oh, I see, I reviewed the wrong method.

**Review by chickenlj — APPROVED** [review]

**Comment by chickenlj** [comment]
LGTM.

**Review by AlbumenJ — APPROVED** [review]
LGTM.
