### PR TITLE
Fix NetUtils: should ignore link-local address

### LINKED ISSUE #14792: [Bug] NetUtils should ignore the local link address
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Any

### Steps to reproduce this issue

In the K8S scenario, some applications may have two NICs, eth0 and veth0, and eth0 is configured with a real physical address. veth0 is configured with a local link address, which may randomly select the local link address to veth0, resulting in unavailability of the service.

When I look at the netUtils code, I see that netutils only ignores the lookback address, not the local link address.

https://github.com/mercyblitz/dubbo/blob/d8a4acd13c8270bdefe38f8b109dee457ee15593/dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java#L148

### What you expected to happen

NetUtils should ignore the local link address

### Anything else

_No response_

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cyclinder**
## What is the purpose of the change?

NetUtils: should be ignore link-local address

Fixes https://github.com/apache/dubbo/issues/14792

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Make sure gitHub actions can pass. [Why the workflow is failing and how to fix it?](./CONTRIBUTING.md)

### CODE REVIEW

**Comment by heliang666s** [comment]
LGTM

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java [hunk 1]
```diff
@@ -196,7 +196,7 @@ public static InetSocketAddress getLocalSocketAddress(String host, int port) {
     }
 
     static boolean isValidV4Address(InetAddress address) {
-        if (address == null || address.isLoopbackAddress()) {
+        if (address == null || address.isLoopbackAddress() || address.isLinkLocalAddress()) {
```
Comment (AlbumenJ) [inline dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java:199]: What would happen if there is no any non-local interface

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java (hunk 1 above)
Comment (yunmaoQu) [inline dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java:199]: @AlbumenJ Just suggesstion:add a parameter called  "allowLinkLocal(boolean)" in some related method( i find two extend point from original structure) .And user can config the value in system config file while  it's default value is true to  prevent the situation that though there is no any non-local interface and it also work ,  it's  ok?

Comment (yunmaoQu) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java:199]: i've done the work in local,if my idea is available and need my code ,i 'll push a request under this issue!

Comment (cyclinder) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java:199]: if there is no non-local address, `address.isLinkLocalAddress()` would return false, This function wouldn't return directly, Continue with the logic below, same as if it was a lookback address.

Comment (cyclinder) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java:199]: Refer to https://github.com/apache/dubbo/pull/14793/files#r1814182854, `address.isLinkLocalAddress()` shouldn't affect if there is no non-local address. I don't have a Dubbo environment locally, Can you help test the changes? thanks a lot.
