### PR TITLE
fail fast when protocol exp

### LINKED ISSUE #12359: Error exception prompt when the protocol does not exist
### Environment

* Dubbo version: 3.2.1
* Operating System version: mac m1
* Java version: 1.8

### Steps to reproduce this issue

1. Pull the latest source code of dubbo3.2

2. Start the demo provider project, dubbo-springboot-demo-provider

3. Start the demo comsumer project, dubbo-springboot-demo-comsuer。Configure  as follow:

   ```
   dubbo.consumer.protocol:  unknown  //does not exist
   ```

   

### Expected Behavior

Comuser fails to start and reports that the protocol does not exist

### Actual Behavior

Consumer failed to start and printed an unrelated exception

```
[20/05/23 23:43:14:894 CST] main ERROR deploy.DefaultModuleDeployer:  [DUBBO] Model start failed: Dubbo Module[1.1.1] start failed: java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.springboot.demo.DemoService. No provider available for the service org.apache.dubbo.springboot.demo.DemoService from the url fgh://192.168.1.105/org.apache.dubbo.springboot.demo.DemoService?application=dubbo-springboot-demo-consumer&background=false&dubbo=2.0.2&executor-management-mode=isolation&file-cache=true&interface=org.apache.dubbo.springboot.demo.DemoService&methods=sayHello,sayHelloAsync&pid=24800&protocol=fgh&qos.enable=true&qos.port=33333&register.ip=192.168.1.105&release=&side=consumer&sticky=false&timestamp=1684597394299&unloadClusterRelated=false to the consumer 192.168.1.105 use dubbo version , dubbo version: , current host: 192.168.1.105, error code: 5-14. This may be caused by , go to https://dubbo.apache.org/faq/5/14 to find instructions. 
java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.springboot.demo.DemoService. No provider available for the service org.apache.dubbo.springboot.demo.DemoService from the url fgh://192.168.1.105/org.apache.dubbo.springboot.demo.DemoService?application=dubbo-springboot-demo-consumer&background=false&dubbo=2.0.2&executor-management-mode=isolation&file-cache=true&interface=org.apache.dubbo.springboot.demo.DemoService&methods=sayHello,sayHelloAsync&pid=24800&protocol=fgh&qos.enable=true&qos.port=33333&register.ip=192.168.1.105&release=&side=consumer&sticky=false&timestamp=1684597394299&unloadClusterRelated=false to the consumer 192.168.1.105 use dubbo version 
	at org.apache.dubbo.config.ReferenceConfig.checkInvokerAvailable(ReferenceConfig.java:647)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:311)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:232)
	at org.apache.dubbo.config.utils.SimpleReferenceCache.destroyReference(SimpleReferenceCache.java:265)
	at org.apache.dubbo.config.utils.SimpleReferenceCache.destroy(SimpleReferenceCache.java:218)
	at org.apache.dubbo.config.utils.SimpleReferenceCache.destroy(SimpleReferenceCache.java:242)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:444)
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:419)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:173)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:145)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:113)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:102)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:47)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:940)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at org.apache.dubbo.springboot.demo.consumer.ConsumerApplication.main(ConsumerApplication.java:38)
```

### PR DESCRIPTION
**Pull request by wxbty**
## What is the purpose of the change
fix #12359 
pr #12316  modifies the status when the module fails to start, thus preventing DefaultApplicationDeployer#prepareApplicationInstance from running.
In addition to exposing metadataService, prepareApplicationInstance also includes protocol extension verification. When the comsumer configures the wrong protocol, the wrong prompt is printed.

## Brief changelog
There is no problem with the modification of pr #12316. We need to fail fast when building the Invoker step to verify the serialization protocol, and do not perform subsequent steps

## Verifying this change
Following the steps in #12359, gives the expected result

### CODE REVIEW

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java [hunk 1]
```diff
@@ -447,6 +448,12 @@ private boolean checkProtocolValid(String queryProtocols, URL providerUrl) {
                 if (providerUrl.getProtocol().equals(acceptProtocol)) {
                     accept = true;
                     break;
+                } else {
+                    try {
+                        moduleModel.getApplicationModel().getExtensionLoader(Protocol.class).getExtension(acceptProtocol);
```
Comment (AlbumenJ) [inline dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java:453]: Use `hasExtension` would be better

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

**Review by AlbumenJ — COMMENTED** [review]
Do we prepend to do this type check at initialization time. I think this modification is in the notify process. If dirty data is wrongly written in the registry (or an updated protocol, which usually occurs in the version iteration process), this will cause the processing of this push to be directly abnormal. , causing a greater impact.

**Comment by wxbty** [comment]
> Do we prepend to do this type check at initialization time. I think this modification is in the notify process. If dirty data is wrongly written in the registry (or an updated protocol, which usually occurs in the version iteration process), this will cause the processing of this push to be directly abnormal. , causing a greater impact.

The above is the thread stack of the current protocol verification, which is located in the process ReferenceConfig.init -> ReferenceConfig.createInvoker. Before the metadata is pushed, it seems that the registration center has not yet been pushed. Where do you want the protocol validation to be?

**Comment by wxbty** [comment]
> > > Do we prepend to do this type check at initialization time. I think this modification is in the notify process. If dirty data is wrongly written in the registry (or an updated protocol, which usually occurs in the version iteration process), this will cause the processing of this push to be directly abnormal. , causing a greater impact.
> > 
> > 
> > ```
> > [21/05/23 21:16:44:231 CST] main ERROR zookeeper.ZookeeperRegistry:  [DUBBO] Failed to notify addresses for subscribe unknown://192.168.1.2/org.apache.dubbo.springboot.demo.DemoService?application=dubbo-springboot-demo-consumer&background=false&category=providers,configurators,routers&dubbo=2.0.2&executor-management-mode=isolation&file-cache=true&interface=org.apache.dubbo.springboot.demo.DemoService&methods=sayHello,sayHelloAsync&pid=1590&protocol=unknown&qos.enable=true&qos.port=33333&release=3.2.2-SNAPSHOT&side=consumer&sticky=false&timestamp=1684674910080&unloadClusterRelated=false, cause: java.lang.IllegalStateException: No such extension org.apache.dubbo.rpc.Protocol by name unknown, no related exception was found, please check whether related SPI module is missing., dubbo version: 3.2.2-SNAPSHOT, current host: 192.168.1.2, error code: 1-7. This may be caused by , go to https://dubbo.apache.org/faq/1/7 to find instructions. 
> > org.apache.dubbo.registry.support.SkipFailbackWrapperException: java.lang.IllegalStateException: No such extension org.apache.dubbo.rpc.Protocol by name unknown, no related exception was found, please check whether related SPI module is missing.
> > Caused by: java.lang.IllegalStateException: No such extension org.apache.dubbo.rpc.Protocol by name unknown, no related exception was found, please check whether related SPI module is missing.
> > 	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:779)
> > 	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:786)
> > 	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:575)
> > 	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:549)
> > 	at org.apache.dubbo.registry.integration.RegistryDirectory.checkProtocolValid(RegistryDirectory.java:453)
> > 	at org.apache.dubbo.registry.integration.RegistryDirectory.toInvokers(RegistryDirectory.java:396)
> > 	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshInvoker(RegistryDirectory.java:277)
> > 	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshOverrideAndInvoker(RegistryDirectory.java:218)
> > 	at org.apache.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:194)
> > 	at org.apache.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:533)
> > 	at org.apache.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:376)
> > 	at org.apache.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:365)
> > 	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:306)
> > 	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:88)
> > 	at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:184)
> > 	at org.apache.dubbo.registry.integration.RegistryDirectory.lambda$subscribe$0(RegistryDirectory.java:126)
> > 	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:80)
> > 	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:62)
> > 	at org.apache.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:124)
> > 	at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:591)
> > 	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getInvoker(InterfaceCompatibleRegistryProtocol.java:58)
> > 	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshInterfaceInvoker(MigrationInvoker.java:464)
> > 	at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:245)
> > 	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:76)
> > 	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:60)
> > 	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:249)
> > 	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:556)
> > 	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:526)
> > 	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:508)
> > 	at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.refer(ProtocolSecurityWrapper.java:110)
> > 	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:86)
> > 	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:80)
> > 	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:71)
> > 	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52)
> > 	at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.refer(InvokerCountWrapper.java:48)
> > 	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
> > 	at org.apache.dubbo.config.ReferenceConfig.createInvoker(ReferenceConfig.java:593)
> > 	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:439)
> > 	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:302)
> > 	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:232)
> > 	at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:132)
> > 	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:439)
> > 	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
> > 	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:419)
> > 	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:173)
> > 	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:145)
> > 	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:113)
> > 	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:102)
> > 	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:47)
> > 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
> > 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
> > 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
> > 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
> > 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
> > 	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:940)
> > 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
> > 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
> > 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
> > 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
> > 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
> > 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
> > 	at org.apache.dubbo.springboot.demo.consumer.ConsumerApplication.main(ConsumerApplication.java:38)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The above is the thread stack of the current protocol verification, which is located in the process ReferenceConfig.init -> ReferenceConfig.createInvoker. Before the metadata is pushed, it seems that the registration center has not yet been pushed. Where do you want the protocol validation to be?
> 
> Before listen registry. In `subscribe`

ok

**Review by AlbumenJ — COMMENTED** [review]
org.apache.dubbo.registry.support.AbstractRegistry#subscribe

**Comment by wxbty** [comment]
> org.apache.dubbo.registry.support.AbstractRegistry#subscribe

There are protocols such as consumer that cannot be load
image

**Comment by AlbumenJ** [comment]
> > org.apache.dubbo.registry.support.AbstractRegistry#subscribe
> 
> There are protocols such as consumer that cannot be load image

org/apache/dubbo/registry/integration/RegistryDirectory.java:393

Get protocols from queryMap

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/FailbackRegistry.java [hunk 2]
```diff
@@ -366,6 +366,9 @@ protected void notify(URL url, NotifyListener listener, List<URL> urls) {
         } catch (Exception t) {
             // Record a failed registration request to a failed list
             logger.error(REGISTRY_FAILED_NOTIFY_EVENT, "", "", "Failed to notify addresses for subscribe " + url + ", cause: " + t.getMessage(), t);
+            if (t instanceof SkipFailbackWrapperException) {
+                throw t;
+            }
```
Comment (AlbumenJ) [inline dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/FailbackRegistry.java:371]: Is these still necessary

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/FailbackRegistry.java (hunk 2 above)
Comment (wxbty) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/FailbackRegistry.java]: will remove it

**Review by AlbumenJ — APPROVED** [review]
