### PR TITLE
[3.3] Set FQCN for FluentLoggerImpl

### LINKED ISSUE #15240: [Bug] FluentLoggerImpl doesn't record the code line number of the calling class, and just record its own calling time
### Pre-check

- [x] I am sure that all the content I provide is in English.

### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo 3.3

### Steps to reproduce this issue

the delegate of FluentLoggerImpl is org.apache.dubbo.common.logger.slf4j.Slf4jLogger, which has already set FQCN, so the code line numbers that FluentLoggerImpl outputs are all his own.
Image
the timestamp recorded by FluentLoggerImpl does not correspond to the actual time when the application generated the logs. it is just the time when FluentLoggerImpl called the logger agent.This may cause inconsistencies in timestamp alignment between client and server logs, make it challenging to determine the chronological order of interactions between the client and server.

### What you expected to happen

the code line number of log info should be the code line number of the calling class.

### Anything else

_No response_

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zrlw**
## What is the purpose of the change?
fix #15240

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Make sure gitHub actions can pass. [Why the workflow is failing and how to fix it?](../CONTRIBUTING.md)

### CODE REVIEW

File: dubbo-common/src/main/java/org/apache/dubbo/common/logger/log4j2/Log4j2Logger.java [hunk 1]
```diff
@@ -17,113 +17,129 @@
...
-    public Log4j2Logger(org.apache.logging.log4j.Logger logger) {
+    public Log4j2Logger(String fqcn, org.apache.logging.log4j.spi.ExtendedLogger logger) {
+        this.fqcn = fqcn;
         this.logger = logger;
     }
 
     @Override
     public void trace(String msg) {
-        logger.trace(msg);
+        logger.logIfEnabled(fqcn, Level.TRACE, null, logger.getMessageFactory().newMessage(msg), null);
```
Comment (oxsean) [inline dubbo-common/src/main/java/org/apache/dubbo/common/logger/log4j2/Log4j2Logger.java]: Why not use `void logIfEnabled(String fqcn, Level level, Marker marker, String message)`

File: dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java [hunk 2]
```diff
@@ -193,6 +193,32 @@ public static ErrorTypeAwareLogger getErrorTypeAwareLogger(String key) {
...
+     * Get error type aware logger by FQCN and Class object.
+     *
+     * @param fqcn the full qualified class name of caller
+     * @param key the returned logger will be named after clazz
+     * @return error type aware logger
+     */
+    public static ErrorTypeAwareLogger getErrorTypeAwareLogger(String fqcn, Class<?> key) {
+        return ConcurrentHashMapUtils.computeIfAbsent(
+                ERROR_TYPE_AWARE_LOGGERS,
+                key.getName(),
```
Comment (oxsean) [inline dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java]: key.getName() -> Pair.of(key.getName(), fqcn)

File: dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java [hunk 3]
```diff
@@ -193,6 +193,32 @@ public static ErrorTypeAwareLogger getErrorTypeAwareLogger(String key) {
...
+
+    /**
+     * Get error type aware logger by FQCN and a String key.
+     *
+     * @param fqcn the full qualified class name of caller
+     * @param key the returned logger will be named after key
+     * @return error type aware logger
+     */
+    public static ErrorTypeAwareLogger getErrorTypeAwareLogger(String fqcn, String key) {
+        return ConcurrentHashMapUtils.computeIfAbsent(
```
Comment (oxsean) [inline dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java:219]: key -> Pair.of(key, fqcn)

File: dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java [hunk 4]
```diff
@@ -43,7 +44,7 @@
 public class LoggerFactory {
 
     private static final ConcurrentMap<String, FailsafeLogger> LOGGERS = new ConcurrentHashMap<>();
-    private static final ConcurrentMap<String, FailsafeErrorTypeAwareLogger> ERROR_TYPE_AWARE_LOGGERS =
+    private static final ConcurrentMap<Pair<String, Object>, FailsafeErrorTypeAwareLogger> ERROR_TYPE_AWARE_LOGGERS =
```
Comment (oxsean) [inline dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java]: ConcurrentMap<Object, FailsafeErrorTypeAwareLogger>

File: dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java [hunk 5]
```diff
@@ -178,8 +179,8 @@ public static Logger getLogger(String key) {
     public static ErrorTypeAwareLogger getErrorTypeAwareLogger(Class<?> key) {
         return ConcurrentHashMapUtils.computeIfAbsent(
                 ERROR_TYPE_AWARE_LOGGERS,
-                key.getName(),
-                name -> new FailsafeErrorTypeAwareLogger(loggerAdapter.getLogger(name)));
+                Pair.of(FailsafeLogger.class.getName(), key),
```
Comment (oxsean) [inline dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java]: No changes necessary.

File: dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java [hunk 6]
```diff
@@ -190,7 +191,37 @@ public static ErrorTypeAwareLogger getErrorTypeAwareLogger(Class<?> key) {
      */
     public static ErrorTypeAwareLogger getErrorTypeAwareLogger(String key) {
         return ConcurrentHashMapUtils.computeIfAbsent(
-                ERROR_TYPE_AWARE_LOGGERS, key, k -> new FailsafeErrorTypeAwareLogger(loggerAdapter.getLogger(k)));
+                ERROR_TYPE_AWARE_LOGGERS,
```
Comment (oxsean) [inline dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java]: No changes necessary.

File: dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerAdapter.java [hunk 7]
```diff
@@ -43,6 +44,18 @@ public interface LoggerAdapter {
...
     Logger getLogger(String key);
 
+    /**
+     * Get a logger
+     *
+     * @param pair the left of the pair is the full qualified class name of caller,
+     *             the right of it is clazz or key that the returned logger will be named after.
+     * @return logger
+     */
+    default Logger getLogger(Pair<String, Object> pair) {
```
Comment (oxsean) [inline dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerAdapter.java]: The previous version was clearer.

**Review by oxsean — CHANGES_REQUESTED** [review]
Just change the key type from string to object.

File: dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java [hunk 8]
```diff
@@ -190,7 +191,37 @@ public static ErrorTypeAwareLogger getErrorTypeAwareLogger(Class<?> key) {
...
+     * Get error type aware logger by FQCN and Class object.
+     *
+     * @param fqcn the full qualified class name of caller
+     * @param key the returned logger will be named after clazz
+     * @return error type aware logger
+     */
+    public static ErrorTypeAwareLogger getErrorTypeAwareLogger(String fqcn, Class<?> key) {
+        return ConcurrentHashMapUtils.computeIfAbsent(
+                ERROR_TYPE_AWARE_LOGGERS,
+                Pair.of(fqcn, key),
```
Comment (oxsean) [inline dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java]: Pair.of(key, fqcn) 
Put the highly distinctive ones at the beginning.

**Review by oxsean — APPROVED** [review]

**Review by oxsean — APPROVED** [review]
LGTM.
