### PR TITLE
[3.3] Add connection preface process to TripleHttp2Protocol

### LINKED ISSUE #15233: [Bug] No provider available due to receiving go away frame immediately after successful connection
### Pre-check

- [x] I am sure that all the content I provide is in English.

### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo 3.3

### Steps to reproduce this issue

it happened occationally, see details at https://github.com/apache/dubbo/actions/runs/13742828420/job/38434341835
Image

### What you expected to happen
this issue should not happen.

### Anything else

_No response_

### Are you willing to submit a pull request to fix on your own?

- [x] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zrlw**
## What is the purpose of the change?
fixed #15233 ```No provider available``` issue, the roots of the issue is client sent large headers frame before receiving server connection preface (http2 settings frame), which cause server sent back go away frame and the connection was disconnected by the server.
go away issue
see details at https://httpwg.org/specs/rfc7540.html#ConnectionHeader
```
3.5. HTTP/2 Connection Preface
In HTTP/2, each endpoint is required to send a connection preface as a final confirmation of the protocol in use and to establish the initial settings for the HTTP/2 connection. The client and server each send a different connection preface.
The client connection preface starts with a sequence of 24 octets, which in hex notation is:
0x505249202a20485454502f322e300d0a0d0a534d0d0a0d0a
That is, the connection preface starts with the string PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n). This sequence MUST be followed by a SETTINGS frame (Section 6.5), which MAY be empty. 
... ...
The server connection preface consists of a potentially empty SETTINGS frame (Section 6.5) that MUST be the first frame the server sends in the HTTP/2 connection.
```

https://quafoo.gitbooks.io/http2-rfc7540-zh-cn-en/content/chapter3/section3.5.html
```
HTTP/2 Connection Preface / HTTP/2连接前奏
在HTTP/2中，要求两端都要发送一个连接前奏，作为对所使用协议的最终确认，并确定HTTP/2连接的初始设置。客户端和服务端各自发送不同的连接前奏。
客户端连接前奏以一个24字节的序列开始，用十六进制表示为：
0x505249202a20485454502f322e300d0a0d0a534d0d0a0d0a
即，连接前奏以字符串"PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"开始。这个序列后面必须跟一个可以为空的 SETTINGS 帧( 6.5节 )。
... ...
服务端连接前奏包含一个可能为空的 SETTINGS 帧( 6.5节 )，它必须由服务端在HTTP/2连接中首先发送。
```

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Make sure gitHub actions can pass. [Why the workflow is failing and how to fix it?](../CONTRIBUTING.md)

### CODE REVIEW

**Review by AlbumenJ — APPROVED** [review]
@oxsean PTAL

**Comment by zrlw** [comment]
refer to okhttp:
```
Http2.java
  static final ByteString CONNECTION_PREFACE
      = ByteString.encodeUtf8("PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n");

Http2Reader.java
  public void readConnectionPreface(Handler handler) throws IOException {
    if (client) {
      // The client reads the initial SETTINGS frame.
      if (!nextFrame(true, handler)) {
        throw ioException("Required SETTINGS preface not received");
      }
    } else {
      // The server reads the CONNECTION_PREFACE byte string.
      ByteString connectionPreface = source.readByteString(CONNECTION_PREFACE.size());
      if (logger.isLoggable(FINE)) logger.fine(format("<< CONNECTION %s", connectionPreface.hex()));
      if (!CONNECTION_PREFACE.equals(connectionPreface)) {
        throw ioException("Expected a connection header but was %s", connectionPreface.utf8());
      }
    }
  }
```

File: dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/AbstractNettyConnectionClient.java [hunk 1]
```diff
@@ -168,6 +181,35 @@ protected void doConnect() throws RemotingException {
 
             throw remotingException;
         }
+
+        if (connectionPrefaceReceivedPromise != null) {
```
Comment (oxsean) [inline dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/AbstractNettyConnectionClient.java:185]: Why not handle it in connect? I think it's not appropriate to do it in initBootstrap

**Comment by oxsean** [comment]
Sorry for late, But I think it's better to merge the PR after the review.

File: dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/AbstractNettyConnectionClient.java [hunk 2]
```diff
@@ -57,6 +57,8 @@ public abstract class AbstractNettyConnectionClient extends AbstractConnectionCl
 
     private ConnectionListener connectionListener;
 
+    private AtomicReference<Promise<Void>> connectionPrefaceReceivedPromiseRef;
+
     public static final AttributeKey<AbstractConnectionClient> CONNECTION = AttributeKey.valueOf("connection");
 
     public AbstractNettyConnectionClient(URL url, ChannelHandler handler) throws RemotingException {
```
Comment (oxsean) [inline dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/AbstractNettyConnectionClient.java:64]: I think this logic should be added to `org.apache.dubbo.remoting.transport.netty4.NettyConnectionClient`, because HTTP/3 probably doesn't need it."

**Comment by oxsean** [comment]
@zrlw @AlbumenJ I think we can just make some changes in NettyConnectionClient, move the TripleHttp2SettingsHandler setup there and deal with it — no need modify other classes.

**Comment by zrlw** [comment]
this pr was reverted because i found it has problems which should be fixed, and i want to find a more elegant way to do it.

**Comment by zrlw** [comment]
> @zrlw @AlbumenJ I think we can just make some changes in NettyConnectionClient, move the TripleHttp2SettingsHandler setup there and deal with it — no need modify other classes.

how to know the protol of current NettyConnectionClient is http2?

**Comment by zrlw** [comment]
submit a new pr: https://github.com/apache/dubbo/pull/15436
