### PR TITLE
remind user to add qos dependency.(Fixes #10682)

### LINKED ISSUE #10682: Connect to QoS failed.
I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository. There is a similar issue #10198. I did as the issue described, but still failed.

### Environment

* Dubbo version: branch 3.1
* Operating System version: win7
* Java version: 11

### Steps to reproduce this issue

1. modify the dubbo.properties in [dubbo-demo-xml-provider](https://github.com/apache/dubbo/tree/3.1/dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider)
`dubbo.application.qos-enable=true`
`dubbo.application.qos-port=33333`
`dubbo.application.qos-accept-foreign-ip=true`
2. run dubbo-demo-xml-provider

### Expected Behavior

`telnet {ip} 33333` will connect to QoS server successfully.

### Actual Behavior

There is no exception. Provider is successfully started and running.

### PR DESCRIPTION
**Pull request by pandaapo**
## What is the purpose of the change
Fixes #10682

## Brief changelog
Although configure `dubbo.application.qos-enable=true`, it may not work. You may find provider is started successfully without qos server.
In fact, qos dependency is necessary for qos server to start successfully. But the reason is not obvious.
~~So I define an annotation `@QosServer`. It has no function, but can guide developers to import qos dependency.~~
I check `qos-enable` during app startup. When there is no `qos-enable=false` and no dubbo-qos dependency, `logg.warn` some information.

## Verifying this change
run [dubbo-demo-xml-provider](https://github.com/apache/dubbo/tree/3.1/dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider)

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

File: dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/annotation/QosServer.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+import java.lang.annotation.Target;
+
+/**
+ * Prompt to add dubbo qos dependency. If you know qos dependency is needed or it has been added,
+ * you don't have to write this annotation.
+ */
+@Retention(RetentionPolicy.SOURCE)
+@Target(ElementType.TYPE)
+public @interface QosServer {
+}
```
Comment (AlbumenJ) [inline dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/annotation/QosServer.java:31]: Was it better to use a logger to log out when user config `dubbo.application.qos-xxx` if dubbo-qos denendency is absent?

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

File: dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/annotation/QosServer.java (hunk 1 above)
Comment (leopardrota) [reply dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/annotation/QosServer.java:31]: `dubbo.application.qos-enable` has default value `true`. Does it make user think qos should start although there is no any qos configuration(system property, dubbo.properties, xml or springboot autoconfigure) in project?

Comment (AlbumenJ) [reply dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/annotation/QosServer.java:31]: ok.

I think it would be better to log out what current environment have / do not have as a info message. Including `dubbo-qos`, `dubbo-registry-xxx`, `dubbo-rpc-xxx`...

File: dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java [hunk 2]
```diff
@@ -295,6 +295,14 @@ private void checkConfigs() {
...
             protocolPortMap.put(port, protocol);
         }
+
+        // Log the current configurations.
+        logger.info("The current configurations or effective configurations are as follows:");
+        for (Class<? extends AbstractConfig> configType : multipleConfigTypes) {
+            getConfigs(configType).stream().forEach((config) -> {
+                logger.info(config.toString());
+            });
+        }
```
Comment (AlbumenJ) [inline dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java:305]: Will this work?

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

**Comment by AlbumenJ** [comment]
please fix uts

**Comment by AlbumenJ** [comment]
image

**Comment by AlbumenJ** [comment]
> > image
> 
> I want to test `ConfigValidationUtils#checkQosDependency()` even though it is private, but the method has no testable item except `logger#warn()`. So I intend to mock `logger` field, but it's a final field. I have to handle it with reflection. Now JDK17 seems forbid this operation for safety. I have no another good idea for now. Should I just test whether this method can be called by `#validateApplicationConfig()` correctly, not the inner logic? Could you give me some better suggestions?
> 
> 想测试`ConfigValidationUtils#checkQosDependency()`方法（虽然是私有方法），但是该方法没有返回值、没有抛异常之类的可测试项，只有logger打印日志。于是就考虑注入Mock(logger)，但是logger是final字段，只好利用反射来处理下，但是JDK17好像为提高安全性不支持这种操作。一时间没想到好办法。 考虑放弃测试该方法内部，只测试该方法是否能被 `#validateApplicationConfig()`正确调用。能否提供一些其他解决思路？谢谢。

junit 可以配置验证的版本，配置 range 到 jdk 14 就行

**Comment by AlbumenJ** [comment]
> > > 想测试`ConfigValidationUtils#checkQosDependency()`方法（虽然是私有方法），该方法没有返回值、没有抛异常之类的可测试项，只有logger打印日志。于是就考虑注入Mock(logger)，但是logger是final字段，只好利用反射来处理下，但是JDK17好像为提高安全性不支持这种操作。一时间没想到好办法。
> > > 考虑放弃测试该方法内部，只测试该方法是否能被 `#validateApplicationConfig()`正确调用。能否提供一些其他解决思路？谢谢。
> > 
> > 
> > junit 可以配置验证的版本，配置 range 到 jdk 14 就行
> 
> 逐版验证了，从jdk 12开始就不行。

是不是 mockstatic 版本太低了

**Comment by pandaapo** [comment]
> > > > 想测试`ConfigValidationUtils#checkQosDependency()`方法（虽然是私有方法），该方法没有返回值、没有抛异常之类的可测试项，只有logger打印日志。于是就考虑注入Mock(logger)，但是logger是final字段，只好利用反射来处理下，但是JDK17好像为提高安全性不支持这种操作。一时间没想到好办法。
> > > > 考虑放弃测试该方法内部，只测试该方法是否能被 `#validateApplicationConfig()`正确调用。能否提供一些其他解决思路？谢谢。
> > > 
> > > 
> > > junit 可以配置验证的版本，配置 range 到 jdk 14 就行
> > 
> > 
> > 逐版验证了，从jdk 12开始就不行。
> 
> 是不是 mockstatic 版本太低了

mockstatic 没问题，ConfigValidationUtils中的静态方法都能正常mock。主要是ConfigValidationUtils中的`logger`是final的，Mock该属性以后没办法注入进去（[即使最新的Mockito也不支持](https://www.javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/InjectMocks.html)），只好利用反射去掉ConfigValidationUtils的Mock类中该字段的final修饰符（但是jdk>=12不支持）。

目前能想到的解决办法有以下3种：
1、把ConfigValidationUtils中的`logger`的final修饰符去掉。（可以验证logger是否打印预期的日志）（适用jdk8\~17）
2、把`ConfigValidationUtils#checkQosDependency()`改成公有方法，并抛出没有Qos依赖的异常。（可以验证是否抛出指定的异常）（适用jdk8\~17）
3、用`MethodHandles.privateLookupIn(Field.class, MethodHandles.lookup())`的反射方式来处理final属性。（可以验证logger是否打印预期的日志）（适用jdk**9**\~14）

**Comment by AlbumenJ** [comment]
> > > > > 想测试`ConfigValidationUtils#checkQosDependency()`方法（虽然是私有方法），该方法没有返回值、没有抛异常之类的可测试项，只有logger打印日志。于是就考虑注入Mock(logger)，但是logger是final字段，只好利用反射来处理下，但是JDK17好像为提高安全性不支持这种操作。一时间没想到好办法。
> > > > > 考虑放弃测试该方法内部，只测试该方法是否能被 `#validateApplicationConfig()`正确调用。能否提供一些其他解决思路？谢谢。
> > > > 
> > > > 
> > > > junit 可以配置验证的版本，配置 range 到 jdk 14 就行
> > > 
> > > 
> > > 逐版验证了，从jdk 12开始就不行。
> > 
> > 
> > 是不是 mockstatic 版本太低了
> 
> mockstatic 没问题，ConfigValidationUtils中公有的静态方法能正常mock（当然私有方法不行，[官方好像也不打算支持](https://github.com/mockito/mockito/issues/2773)）。 主要是ConfigValidationUtils中的`logger`是final的，Mock该属性以后没办法注入进去（[即使最新的Mockito也不支持](https://www.javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/InjectMocks.html)），只好利用反射去掉ConfigValidationUtils的Mock类中该字段的final修饰符，但是jdk>=12不支持。
> 
> 目前能想到的解决办法有以下4种： 1、就是当前PR的：用`Field#getModifiers() & ~Modifier.FINAL`的反射方式来处理final修饰符。（可以测试logger是否打印预期的日志）（适用jdk8~11） 2、直接把ConfigValidationUtils中`logger`的final修饰符去掉。（可以测试logger是否打印预期的日志）（适用jdk8~17） 3、把`ConfigValidationUtils#checkQosDependency()`改成公有方法，并抛出没有Qos依赖的异常。（可以测试是否抛出指定的异常）（适用jdk8~17） 4、用`MethodHandles.privateLookupIn(Field.class, MethodHandles.lookup())`的反射方式来处理final修饰符。（可以测试logger是否打印预期的日志）（适用jdk**9**~14）

用第 2 种吧，3 改成公共方法相对于对外开放了，这个 API 不需要向用户公开的

**Review by AlbumenJ — APPROVED** [review]
LGTM
