### PR TITLE
fix zipkin compatible. #3728

### LINKED ISSUE #3728: examine backward compatibility for Zipkin and Skywalking on 2.7.2
see more from https://github.com/openzipkin/brave/issues/867, also see https://github.com/apache/incubator-dubbo/issues/3576

### PR DESCRIPTION
**Pull request by cvictory**
fix #3728

### CODE REVIEW

**Comment by cvictory** [comment]
在zipkin的sample里测试，结果展示如下：


image

File: dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/FutureAdapter.java [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+                } else {
+                    if (appResponse.hasException()) {
+                        callback.caught(appResponse.getException());
+                    } else {
+                        callback.done((V) appResponse.getValue());
+                    }
+                }
+            }
+        };
+        futureAdapter.getAppResponseFuture().whenComplete(biConsumer);
```
Comment (chickenlj) [inline dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/FutureAdapter.java]: `futureAdapter.getAppResponseFuture()` seems unnecessary, we can use CompletableFuture directly, there's no need to convert to `FutureAdapter` and use get it's internal `appResponseFuture`. 

What do you think？
