### PR TITLE
fix #11986 ConcurrentHashMapUtils lock bug

### LINKED ISSUE #11986: ConcurrentHashMapUtils无法解决jdk8的循环bug
### Environment

* Dubbo version: 3.2, 3.3
* Operating System version: Windows11
* Java version: jdk8

### Steps to reproduce this issue

[ConcurrentHashMapUtils](https://github.com/apache/dubbo/blob/3.2/dubbo-common/src/main/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtils.java) 中提供的`computeIfAbsent`方法没有解决jdk8的循环问题，复现代码如下：

```java
final ConcurrentHashMap<String,Integer> map=new ConcurrentHashMap<>();
// // map.computeIfAbsent("AaAa", key->map.computeIfAbsent("BBBB",key2->42));
ConcurrentHashMapUtils.computeIfAbsent(map, "AaAa", key->map.computeIfAbsent("BBBB",key2->42));
```

[Hutool](https://github.com/dromara/hutool) 中的解决方案是：

```java
V value = map.get(key);
if (null == value) {
	map.putIfAbsent(key, mappingFunction.apply(key));
	value = map.get(key);
}
return value;
```

### PR DESCRIPTION
**Pull request by looly**
## What is the purpose of the change

fix ConcurrentHashMapUtils lock bug

## Verifying this change

Closed #11986 

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [x] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by looly** [comment]
issue : https://github.com/apache/dubbo/issues/11986

**Comment by AlbumenJ** [comment]
image

File: dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java [hunk 1]
```diff
@@ -37,4 +37,17 @@ public void testComputeIfAbsent() {
         ifAbsent = ConcurrentHashMapUtils.computeIfAbsent(map, "mxsm", k -> "mxsm1");
         assertEquals("mxsm1", ifAbsent);
     }
+
+    @Test
+    public void issue11986Test(){
+        // https://github.com/apache/dubbo/issues/11986
+        final ConcurrentHashMap<String,Integer> map=new ConcurrentHashMap<>();
+        // // map.computeIfAbsent("AaAa", key->map.computeIfAbsent("BBBB",key2->42));
+        if (JRE.JAVA_8.isCurrentVersion()) {
```
Comment (AlbumenJ) [inline dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java:46]: 这里应该任何版本的 JDK 都应该可以使用吧

Comment (looly) [reply dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java:46]: 并不是。这个bug在JDK8下会造成循环调用，但是jdk9+修复了这个问题，解决方式是有循环调用则抛出异常。这个test在jdk8下通过，jdk9+抛出异常。

**Review by KamToHung — COMMENTED** [review]
https://github.com/apache/dubbo/pull/6032
ExtensionLoader以前也遇到过这种问题，这样修改后代码健壮性挺好的

File: dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java (hunk 1 above)
Comment (AlbumenJ) [reply dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java:46]: 那基于 junit5 的注解做两个测试吧
现在 PR的 UT 只跑 JDK17，JDK 8 11 17 的全量测试只有 scheduled 的时候跑

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

File: dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java (hunk 1 above)
Comment (looly) [reply dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java:47]: @AlbumenJ 是这个意思么？我拆分成两个test。

Comment (AlbumenJ) [reply dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java:47]:
```
    @EnabledForJreRange(max = JRE.JAVA_8)
    @EnabledForJreRange(min = JRE.JAVA_9)
```

Comment (AlbumenJ) [reply dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java:47]: 写两个 test，分别通过 EnabledForJreRange 配置运行的 jdk 版本

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

File: dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java (hunk 1 above)
Comment (looly) [reply dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java]: @AlbumenJ 辛苦看下。

File: dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java [hunk 2]
```diff
@@ -37,4 +39,31 @@ public void testComputeIfAbsent() {
...
+
+    @Test
+    @EnabledForJreRange(max = org.junit.jupiter.api.condition.JRE.JAVA_8)
+    public void issue11986ForJava8Test(){
+        // https://github.com/apache/dubbo/issues/11986
+        final ConcurrentHashMap<String,Integer> map=new ConcurrentHashMap<>();
+        // // map.computeIfAbsent("AaAa", key->map.computeIfAbsent("BBBB",key2->42));
+
+        // JDK8下，由于循环调用bug，会造成执行computeIfAbsent死循环问题
+        // ConcurrentHashMapUtils.computeIfAbsent用于解决此问题，保证正常执行
```
Comment (AlbumenJ) [inline dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtilsTest.java:51]: Please comment in English

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtils.java [hunk 3]
```diff
@@ -35,7 +35,18 @@ public static <K, V> V computeIfAbsent(ConcurrentMap<K, V> map, K key, Function<
         if (JRE.JAVA_8.isCurrentVersion()) {
             V v = map.get(key);
             if (null == v) {
-                v = map.computeIfAbsent(key, func);
+                // issue#11986 lock bug
+                // v = map.computeIfAbsent(key, func);
+
+                // this bug fix methods maybe cause `func.apply` multiple calls.
+                v = func.apply(key);
```
Comment (AlbumenJ) [inline dubbo-common/src/main/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtils.java:42]: Will this allocate more memory?

Comment (looly) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtils.java:42]: yes

Comment (CrazyHZM) [inline dubbo-common/src/main/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtils.java:42]: Please check whether v is null.

**Review by CrazyHZM — CHANGES_REQUESTED** [review]

**Review by CrazyHZM — APPROVED** [review]
