### PR TITLE
[2.7] fix memory leak

### LINKED ISSUE #10219: 内存溢出
利用dubbo进行小文件二进制byte[]传输时，在提供方端byte[]对象无法被回收导致内存溢出

版本        
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-dubbo</artifactId>
            <version>2.2.3.RELEASE</version>
        </dependency>
图片

图片

图片

### PR DESCRIPTION
**Pull request by icodening**
## What is the purpose of the change
fix #10219

## Brief changelog
remove ``ThreadLocal`` from ``Hessian2ObjectInput`` and ``Hessian2ObjectOutput ``

### CODE REVIEW

File: dubbo-common/src/main/java/org/apache/dubbo/common/io/UnsafeByteArrayOutputStream.java [hunk 1]
```diff
@@ -97,5 +97,7 @@ public String toString(String charset) throws UnsupportedEncodingException {
 
     @Override
     public void close() throws IOException {
+        this.mBuffer = new byte[0];
```
Comment (flacocobot) [inline dubbo-common/src/main/java/org/apache/dubbo/common/io/UnsafeByteArrayOutputStream.java:100]: This line (100) has been identified with a suspiciousness value of 70.71%.

<details>
     <summary>Failing tests that cover this line</summary>

- `org.apache.dubbo.common.io.BytesTest#testZip`
</details>

File: dubbo-common/src/main/java/org/apache/dubbo/common/io/UnsafeByteArrayOutputStream.java [hunk 2]
```diff
@@ -97,5 +97,7 @@
...
+        this.mCount = 0;
```
Comment (flacocobot) [inline dubbo-common/src/main/java/org/apache/dubbo/common/io/UnsafeByteArrayOutputStream.java:101]: This line (101) has been identified with a suspiciousness value of 70.71%.

<details>
     <summary>Failing tests that cover this line</summary>

- `org.apache.dubbo.common.io.BytesTest#testZip`
</details>

File: dubbo-common/src/main/java/org/apache/dubbo/common/io/UnsafeByteArrayOutputStream.java [hunk 3]
```diff
@@ -97,5 +97,7 @@
...
     }
```
Comment (flacocobot) [inline dubbo-common/src/main/java/org/apache/dubbo/common/io/UnsafeByteArrayOutputStream.java:102]: This line (102) has been identified with a suspiciousness value of 70.71%.

<details>
     <summary>Failing tests that cover this line</summary>

- `org.apache.dubbo.common.io.BytesTest#testZip`
</details>

File: dubbo-common/src/main/java/org/apache/dubbo/common/io/UnsafeByteArrayInputStream.java [hunk 4]
```diff
@@ -102,6 +102,10 @@ public void reset() {
 
     @Override
     public void close() throws IOException {
+        this.mData = new byte[0];
```
Comment (flacocobot) [inline dubbo-common/src/main/java/org/apache/dubbo/common/io/UnsafeByteArrayInputStream.java:105]: This line (105) has been identified with a suspiciousness value of 70.71%.

<details>
     <summary>Failing tests that cover this line</summary>

- `org.apache.dubbo.common.io.BytesTest#testZip`
</details>

File: dubbo-common/src/main/java/org/apache/dubbo/common/io/UnsafeByteArrayInputStream.java [hunk 5]
```diff
@@ -102,6 +102,10 @@
...
+        this.mPosition = 0;
```
Comment (flacocobot) [inline dubbo-common/src/main/java/org/apache/dubbo/common/io/UnsafeByteArrayInputStream.java:106]: This line (106) has been identified with a suspiciousness value of 70.71%.

<details>
     <summary>Failing tests that cover this line</summary>

- `org.apache.dubbo.common.io.BytesTest#testZip`
</details>

**Review by flacocobot — COMMENTED** [review]
[flacoco](https://github.com/SpoonLabs/flacoco) flags 5 suspicious lines as the potential root cause of the test failure.

**Comment by icodening** [comment]
@AlbumenJ the pr had remove ``ThreadLocal`` to fix issue #10219, pls review

**Review by AlbumenJ — APPROVED** [review]
