### PR TITLE
[3.3] Enable server socket reuseAddress option before binding

### LINKED ISSUE #15238: [Bug] sometimes the port got from NetUtils#getAvailablePort could not be bound directly
### Pre-check

- [x] I am sure that all the content I provide is in English.

### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo 3.3

### Steps to reproduce this issue

Image

### What you expected to happen

the port that NetUtils#getAvailablePort opened and closed should be reused instantly no matter the port status is TIME-WAIT or not.

### Anything else

_No response_

### Are you willing to submit a pull request to fix on your own?

- [x] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zrlw**
## What is the purpose of the change?
try to fix #15238 
sometimes the port got from NetUtils#getAvailablePort could not be bound directly because the port status is still TIME-WAIT as getAvailablePort closed it without setting SO_REUSEADDR option.

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Make sure gitHub actions can pass. [Why the workflow is failing and how to fix it?](../CONTRIBUTING.md)

### CODE REVIEW

**Comment by oxsean** [comment]
Is it possible to add some tests?

**Comment by zrlw** [comment]
> Is it possible to add some tests?

the results of these codes vary with os and jdk version,
```
ServerSocket serverSocket = new ServerSocket(port);
assertFalse(serverSocket.getReuseAddress());
```
passed if running on win10 + compiled by jdk8,
failed if running on linux + compiled by jdk17 as ```serverSocket.getReuseAddress()``` returns true.
i doubt there should have unified solution.

**Comment by zrlw** [comment]
the reason is net.ipv4.tcp_tw_reuse was set to 1 on my linux, so the reuseAdd option of new serverSocket is true.

**Comment by zrlw** [comment]
see ```SO_REUSEADDR``` at java.net.StandardSocketOptions,
```
Re-use address.
An implementation allows this socket option to be set before the socket is bound or connected. Changing the value of this socket option after the socket is bound has no effect. The default value of this socket option is system dependent.
```
SO_REUSEADDR
since the default value of SO_REUSEADDR is always true on some system, I didn't think of how to write appropriate testing case.
```
    @Test
    void testRepeatedStatusChecking() {
        int port = NetUtils.getAvailablePort();
        for (int i = 0; i < 1000; i++) {
            assertFalse(NetUtils.isPortInUsed(port));
        }
    } 
```

**Comment by zrlw** [comment]
setReuseAddress
Enabling SO_REUSEADDR prior to binding the socket using bind(SocketAddress) allows the socket to be bound even though a previous connection is in a timeout state.

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java [hunk 1]
```diff
@@ -123,7 +123,10 @@ public static synchronized int getAvailablePort(int port) {
             if (USED_PORT.get(i)) {
                 continue;
             }
-            try (ServerSocket ignored = new ServerSocket(i)) {
+            try (ServerSocket serverSocket = new ServerSocket()) {
+                // SO_REUSEADDR should be enabled before bind.
+                serverSocket.setReuseAddress(true);
```
Comment (AlbumenJ) [inline dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java]: Are there any systems which cannot support such configuration or will throw exception here?

Comment (zrlw) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java]: if an error occurs, or the socket is closed,  SocketException will be thrown here.

Comment (zrlw) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java]: i see. Embedded, real time system, or old Unix ( before 1980?) might not support SO_REUSEADDR. added condition check before setting it.

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java [hunk 2]
```diff
@@ -105,6 +105,21 @@ DO NOT replace this logger to error type aware logger (or fail-safe logger), sin
      */
     private static BitSet USED_PORT = new BitSet(65536);
 
+    private static boolean reuseAddressSupported;
+
+    static {
+        try (ServerSocket serverSocket = new ServerSocket()) {
+            serverSocket.setReuseAddress(true);
+            reuseAddressSupported = true;
+        } catch (IOException e) {
```
Comment (AlbumenJ) [inline dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java]:
```suggestion
        } catch (Throwable ignore) {
```

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java (hunk 2 above)
Comment (zrlw) [reply dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java]: done.

**Comment by zrlw** [comment]
there are still somethings need to be revised.
https://github.com/apache/dubbo/actions/runs/13937299977/job/39007599423
testConnection
test

**Comment by zrlw** [comment]
@AlbumenJ PTAL
