### PR TITLE
fix issue: resolve the conficts between Dubbo shutdown hook and Spring.

### LINKED ISSUE #10709: Dubbo Shutdown Hook with Spring Hook
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Describe the proposal

Mark Dubbo Module if is spring managed. Wait spring to close module before execure dubbo shutdown hook.

### PR DESCRIPTION
**Pull request by pandaapo**
## What is the purpose of the change
Fixes #10709

## Brief changelog
Mark Dubbo Module if is spring managed. Wait the module bound to Spring to be handled by Spring before Dubbo shutdown hook executing.

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

File: dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ModuleModel.java [hunk 1]
```diff
@@ -196,4 +197,12 @@ public ConsumerModel registerInternalConsumer(Class<?> internalService, URL url)
         serviceRepository.registerConsumer(consumerModel);
         return consumerModel;
     }
+
+    public boolean isBindSpring() {
```
Comment (AlbumenJ) [inline dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ModuleModel.java:201]: rename to `isLifeCycleManagedExternally`

File: dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java [hunk 2]
```diff
@@ -77,7 +82,44 @@ public void run() {
...
-        applicationModel.destroy();
+        boolean hasModuleBindSpring = false;
+        // check if any modules are bound to Spring
+        for (ModuleModel module: applicationModel.getModuleModels()) {
+            if (module.isBindSpring()) {
+                hasModuleBindSpring = true;
+                break;
+            }
+        }
+        if (hasModuleBindSpring) {
```
Comment (AlbumenJ) [inline dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java:93]: log out to notice user that dubbo is waiting spring to shutdown

File: dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java [hunk 3]
```diff
@@ -77,7 +82,44 @@ public void run() {
...
+                                }
+                            }
+                        }
+                    } catch (InterruptedException e) {
+                        logger.warn(e.getMessage(), e);
+                    }
+                }
+            }
+        }
+        if (!applicationModel.isDestroyed()) {
```
Comment (AlbumenJ) [inline dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java:120]: log out if wait spring failed

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

**Review by AlbumenJ — APPROVED** [review]

**Comment by AlbumenJ** [comment]
image
Please fix uts

**Comment by AlbumenJ** [comment]
LGTM. Could you please add some unit test cases for this PR?

**Review by AlbumenJ — APPROVED** [review]
