### PR TITLE
[master] Fix #9086 NPE

### LINKED ISSUE #9086: getMethodParameter(java.lang.String, java.lang.String, java.lang.String)并发修改导致空指针异常
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.13
* Operating System version: Mac OS、Linux
* Java version: 1.8
* 方法名
org.apache.dubbo.metadata.MetadataInfo.ServiceInfo#getMethodParameter(java.lang.String, java.lang.String, java.lang.String)
### Steps to reproduce this issue
出问题的代码
if (methodParams == null) {
                methodParams = URL.toMethodParameters(params);
                consumerMethodParams = URL.toMethodParameters(consumerParams);
  }
修改为
  Map<String, Map<String, String>> temp = methodParams;
            if (methodParams == null) {
                methodParams = URL.toMethodParameters(params);
                if(temp == null){
                    try {
                        Thread.sleep(1000*3);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
                consumerMethodParams = URL.toMethodParameters(consumerParams);
            }
1. 多线程问题较难复现，采用修改代码的形式模拟
2. 修改代码
3. 在sleep的时间内进行两次请求，第一个请求进入sleep，第二个请求出现空指针异常

### Expected Behavior

正常执行
### Actual Behavior

由于methodParams已经不为空，consumerMethodParams没有被初始化，执行到342行代码时发生空指针

```
Caused by: java.lang.NullPointerException: null
	at org.apache.dubbo.metadata.MetadataInfo$ServiceInfo.getMethodParameter(MetadataInfo.java:353)
	at org.apache.dubbo.metadata.MetadataInfo$ServiceInfo.getMethodParameter(MetadataInfo.java:344)
	at org.apache.dubbo.registry.client.InstanceAddressURL.getServiceMethodParameter(InstanceAddressURL.java:143)
	at org.apache.dubbo.registry.client.InstanceAddressURL.getMethodParameter(InstanceAddressURL.java:156)
	at org.apache.dubbo.common.URL.getMethodParameter(URL.java:881)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.initLoadBalance(AbstractClusterInvoker.java:314)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:263)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:93)
	at org.apache.dubbo.registry.client.migration.ServiceDiscoveryMigrationInvoker.invoke(ServiceDiscoveryMigrationInvoker.java:59)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:96)
	at org.apache.dubbo.common.bytecode.proxy1.sayHello(proxy1.java)

### PR DESCRIPTION
**Pull request by wangchengming666**
fix #9086 NPE

### CODE REVIEW

File: dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java [hunk 1]
```diff
@@ -339,7 +339,10 @@ public String getMethodParameter(String method, String key, String defaultValue)
         }
 
         private String getMethodParameter(String method, String key, Map<String, Map<String, String>> map) {
-            Map<String, String> keyMap = map.get(method);
+            Map<String, String> keyMap = null;
+            if (CollectionUtils.isNotEmptyMap(map)) {
+                keyMap = map.get(method);
+            }
```
Comment (chickenlj) [inline dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java:345]: This check can avoid NPE from happing by checking before use, however, I don't think it can resolve the root  `methodParams` initialization issue as it has a race condition that needs to be resolved.

**Comment by chickenlj** [comment]
Merged as an enhancement for avoiding #9086 NPE from appearing but it cannot resolve the root issue.
