### PR TITLE
[Dubbo-5479] refactor generic invoke support

### LINKED ISSUE #5479: 当设置泛化调用时，consumer生成的代理类没有实现应用的接口
* 启动provider

dubbo-demo-api-provider

* 启动consumer

dubbo-demo-api-consumer

consumer设置generic

```java
    public static void main(String[] args) {
        ReferenceConfig<DemoService> reference = new ReferenceConfig<>();
        reference.setApplication(new ApplicationConfig("dubbo-demo-api-consumer"));
        reference.setRegistry(new RegistryConfig("zookeeper://127.0.0.1:2181"));
        reference.setInterface(DemoService.class);
        reference.setGeneric(true);
        
        Object obj = reference.get();
        for(Class c : obj.getClass().getInterfaces()) {
            System.err.println(c);
        }
        DemoService service = reference.get();
        String message = service.sayHello("dubbo");
        System.out.println(message);
    }
```

客户端会报错：

```
Exception in thread "main" java.lang.ClassCastException: org.apache.dubbo.common.bytecode.proxy0 cannot be cast to org.apache.dubbo.demo.DemoService
	at org.apache.dubbo.demo.consumer.Application.main(Application.java:42)
```

### PR DESCRIPTION
**Pull request by hengyunabc**
## What is the purpose of the change

refactor generic invoke support

## Brief changelog

* A better way to collect interfaces in `AbstractProxyFactory#getProxy`
* fix https://github.com/apache/dubbo/issues/5479

### CODE REVIEW

File: dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyFactory.java [hunk 1]
```diff
@@ -17,28 +17,24 @@
...
 
+import java.util.HashSet;
+import java.util.Set;
+
 /**
  * AbstractProxyFactory
  */
 public abstract class AbstractProxyFactory implements ProxyFactory {
-    private static final Class<?>[] INTERNAL_INTERFACES = new Class<?>[]{
-            EchoService.class, Destroyable.class
```
Comment (chickenlj) [inline dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyFactory.java]: this part is lost in the pr.

File: dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyFactory.java [hunk 2]
```diff
@@ -47,25 +43,31 @@
...
             }
         }
 
-        if (!GenericService.class.isAssignableFrom(invoker.getInterface()) && generic) {
-            interfaces.add(com.alibaba.dubbo.rpc.service.GenericService.class);
-        }
+        interfaces.add(EchoService.class);
+        if (generic) {
+            if (!GenericService.class.isAssignableFrom(invoker.getInterface())) {
+                interfaces.add(GenericService.class);
```
Comment (chickenlj) [inline dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyFactory.java]: `com.alibaba.dubbo.rpc.service.GenericService` should still b supported.

**Comment by chickenlj** [comment]
Please check the comments I left on your PR. I would suggest that you submit a new PR and start work from the latest code in the master branch so as to make sure changes are limited to this specific issue #5479.

**Comment by chickenlj** [comment]
Please remove the changes to the demo module, other changes LGTM.

api/dubbo-demo-api-consumer/src/main/java/org/apache/dubbo/demo/consumer/Application.java
