### PR TITLE
Fix issue #12334.provide broadcast rules to adapt the calling mode.

### LINKED ISSUE #12334: Dubbo 3.2.0 broadcast + injvm not work as expected
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.0 / 3.2.1
* Operating System version: Windows 10
* Java version: OpenJDK 17.0.6

### Steps to reproduce this issue

```java
public interface RemoteCacheSyncService {

  void flushCache();

}

@DubboService
public class RemoteCacheSyncServiceImpl implements RemoteCacheSyncService {

  @Override
  public void flushCache() {
	  // some code			
  }

}
```

We have 3 microservices, referred to as `A`, `B`, and `C`.
Each service contains the above code.

But, just `C` has a `@DubboReference` to the interface only.

```java
@DubboReference(cluster = ClusterRules.BROADCAST)
RemoteCacheSyncService remoteCacheSyncService;
```

### Expected Behavior

Call **ALL** implementations in **ALL** microservices.

### Actual Behavior

However, since there is a service implementation of the interface in the **same application** ( `C` ),
Dubbo will use the `injvm` protocol. Only the service implementation located in `C` will be invoked.

Same issue with https://github.com/apache/dubbo/issues/6842 , however, it came back again.

### PR DESCRIPTION
**Pull request by PhoenixBackendon**
## What is the purpose of the change
Provide broadcast rules to adapt the call mode and provide logs to assist debug.
close #12334 

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Review by namelessssssssssss — APPROVED** [review]
LGTM

File: dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/ScopeClusterInvoker.java [hunk 1]
```diff
@@ -119,14 +127,22 @@ public Class<T> getInterface() {
      */
     @Override
     public Result invoke(Invocation invocation) throws RpcException {
+        // When broadcasting, it should be called remotely.
+        if (BROADCAST_CLUSTER.equalsIgnoreCase(getUrl().getParameter(CLUSTER_KEY))) {
+            logger.debug("Performing broadcast call for method: " + invocation.getMethodName() + " of service: " + getUrl().getServiceKey());
```
Comment (AlbumenJ) [inline dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/ScopeClusterInvoker.java:132]: Check debug enabled here

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

**Review by AlbumenJ — APPROVED** [review]
