### PR TITLE
Clear future in RpcContext when calling sync (#12493)

### LINKED ISSUE #12493: 未及时释放FutureContext造成频繁GC问题
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.12 3.1.8
* Java version: 1.8

### Steps to reproduce this issue

1. consumer及provider 通过环境变量，设置参数 future.sync.set=false
2. provider返回的报文较大
3. 3.0.12版本的调用，dubbo协议不会产生频繁GC问题，triple会产生
4. 3.1.8版本调用，dubbo协议及triple协议都会产生频繁GC问题

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior
Consumer通过dubbo或triple请求，设置了future.sync.set=false  不会在IntenalThreadLocal中保存返回结果，不再产生频繁GC问题

### Actual Behavior
统一设置了参数 future.sync.set=false
**3.0.12版本:**

> Dubbo协议调用 

及时清除了FutureContext，生效原因
image
并在之后响应过程中清除了FutureContext
image
且因参数future.sync.set=false 之后也不再设置FutureContext，从而能够解决频发GC的情况

> Tiple协议调用
 
Tiple未及时清除了FutureContext原因
image
且没有在接收到响应后清除InternalThreadLocal
虽参数future.sync.set=false，但已经将FutureContext设置进了InternalThreadLocal，会造成频繁GC的情况
**3.1.8版本:**
Dubbo协议、Triple协议都没有及时清除FutureContext

> Dubbo协议调用 

image

> Tiple协议调用 

Triple未清除原因 同3.0.12

### PR DESCRIPTION
**Pull request by xlq20080808**
## What is the purpose of the change
fix #12493 

Clear the future in the RpcContext when the request is synchronous and future.sync.set=false 

## Brief changelog
Clear future in RpcContext when calling sync

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [x] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

File: dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java [hunk 1]
```diff
@@ -219,6 +219,8 @@ public Result whenCompleteWithContext(BiConsumer<Result, Throwable> fn) {
         if (setFutureWhenSync || ((RpcInvocation) invocation).getInvokeMode() != InvokeMode.SYNC) {
             // Necessary! update future in context, see https://github.com/apache/dubbo/issues/9461
             RpcContext.getServiceContext().setFuture(new FutureAdapter<>(this.responseFuture));
+        } else {
+            FutureContext.getContext().clearFuture();
```
Comment (AlbumenJ) [inline dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java:223]: Clear here might not a good idea. It would be better to skip set in advance.

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

File: dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java (hunk 1 above)
Comment (xlq20080808) [reply dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java:223]: i will do this

**Comment by xlq20080808** [comment]
Setting futureContext before calling is to allow users to set callbacks in async situations such as TraceFilter. I think it’s not necessary to set it in sync situations.

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java [hunk 2]
```diff
@@ -129,7 +130,9 @@ protected Result doInvoke(final Invocation invocation) throws Throwable {
                 CompletableFuture<AppResponse> appResponseFuture =
                     currentClient.request(request, timeout, executor).thenApply(AppResponse.class::cast);
                 // save for 2.6.x compatibility, for example, TraceFilter in Zipkin uses com.alibaba.xxx.FutureAdapter
-                FutureContext.getContext().setCompatibleFuture(appResponseFuture);
+                if (((RpcInvocation) invocation).getInvokeMode() != InvokeMode.SYNC) {
```
Comment (AlbumenJ) [inline dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java:133]: Check `private static final boolean setFutureWhenSync = Boolean.parseBoolean(System.getProperty(CommonConstants.SET_FUTURE_IN_SYNC_MODE, "true"));`

**Review by AlbumenJ — APPROVED** [review]

File: dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java (hunk 2 above)
Comment (xlq20080808) [reply dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java]: ok

**Review by AlbumenJ — APPROVED** [review]
