### PR TITLE
fix(nacos): Add application key to consumer subscribe URL

### LINKED ISSUE #15843: [Bug] nacos dashboard subscribers application name is unknown
### Pre-check

- [x] I am sure that all the content I provide is in English.

### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo Java 3.3.1 , JDK 17

### Steps to reproduce this issue

I'm use Dubbo spring starter, and  I'm sure my config is correct,  Service-B subscribe Service-A, but In nacos register center, when I query Service-A's subscribers,  the subscriber's Application Name is unknown, 

Image

### What you expected to happen

show the subscriber's Application Name

### Anything else

_No response_

### Are you willing to submit a pull request to fix on your own?

- [x] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ShauryaChauhan1411**
Fixes #15843

The subscriber URL constructed in NacosRegistry for the non-compatible mode was missing the application key, causing the application name to default to "unknown" in the Nacos client metadata. This commit adds the CommonConstants.APPLICATION_KEY parameter using the consumer URL's application name.

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Make sure gitHub actions can pass. [Why the workflow is failing and how to fix it?](../CONTRIBUTING.md)

### CODE REVIEW

File: dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java [hunk 1]
```diff
@@ -290,7 +290,13 @@ private void doSubscribe(final URL url, final NacosAggregateListener listener, f
                         serviceInterface = segments[SERVICE_INTERFACE_INDEX];
                     }
                     URL subscriberURL = url.setPath(serviceInterface)
-                            .addParameters(INTERFACE_KEY, serviceInterface, CHECK_KEY, String.valueOf(false));
+                            .addParameters(
+                                    INTERFACE_KEY,
+                                    serviceInterface,
+                                    CommonConstants.APPLICATION_KEY,
+                                    url.getApplication(), // <-- Your actual fix
```
Comment (heliang666s) [inline dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java]: please remove the useless comment

**Review by heliang666s — CHANGES_REQUESTED** [review]

**Comment by heliang666s** [comment]
please remove: '// <-- Your actual fix'

**Comment by ShauryaChauhan1411** [comment]
@heliang666s:

The unnecessary comment has been removed as requested, and I have pushed the new commit (`style: remove unnecessary comment...`).

I also confirmed the build still passes locally after the change. Ready for your final re-review! Thank you.

**Review by heliang666s — APPROVED** [review]
LGTM

**Review by zrlw — APPROVED** [review]
LGTM
