### PR TITLE
fix metadata service export port incorrect issue

### LINKED ISSUE #10054: [3.0] metadata export port diff with service export port
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.7
* Operating System version: Mac OS
* Java version: 8

### Steps to reproduce this issue

1. set dubbo.protocol.port=30880
2. define dubbo service to export
3. create an @Bean to invoke dubbo reference
4. start up spring boot application
5. service export port is 30880, metadata service export port is 20880

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

metadata service and instance export port is 30880

### Actual Behavior

metadata service and instance export port is 20880

### Issue code debug
image
image
image
image

### PR DESCRIPTION
**Pull request by YoungHu**
## What is the purpose of the change
fix  #10054 

## Brief changelog
use dubbo protocol port as metadata service default export port

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [x] GitHub Actions works fine on your own branch.
- [x] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

File: dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java [hunk 1]
```diff
@@ -111,10 +115,17 @@ private ProtocolConfig generateMetadataProtocol() {
...
                 if (protocol != null && protocol.getServers() != null) {
                     Iterator<ProtocolServer> it = protocol.getServers().iterator();
+                    // metadata service may export before normal service export, it.hasNext() will return false.
+                    // so need use specified protocol port.
                     if (it.hasNext()) {
                         String addr = it.next().getAddress();
                         String rawPort = addr.substring(addr.indexOf(":") + 1);
                         protocolConfig.setPort(Integer.parseInt(rawPort));
+                    } else {
+                        Integer protocolPort = getProtocolConfig(specifiedProtocol).getPort();
```
Comment (guohao) [inline dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java:125]: Why use `protocol port` instead of specified`port` here?

Comment (YoungHu) [reply dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java:125]: because at here specified port is null, then will use random port to export metadata service, which may not same with specified protocol port, then will cause invoke failed.

Comment (chickenlj) [reply dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java:125]: Please check if `getProtocolConfig(specifiedProtocol)` will return null to cause NPE.

Comment (YoungHu) [reply dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java:125]: if `getProtocolConfig(specifiedProtocol)` return null that means application RPC protocol not set. if so, application will startup failed before export metadataService.

Comment (AlbumenJ) [reply dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java:125]: It would be better to throw a customized exception if get protocol failed. Others look good to me.

**Comment by owen200008** [comment]
image
@PostConstruct use dubbo call, it must be port error, metadata use 20880
protocalconfig no load

**Comment by owen200008** [comment]
use dubbo.application.metadata-service-port=31052 ?

**Comment by AlbumenJ** [comment]
> use dubbo.application.metadata-service-port=31052 ?

After apply this PR?

**Comment by owen200008** [comment]
> > use dubbo.application.metadata-service-port=31052 ?
> 
> After apply this PR?

no, i use version 3.0.9

**Comment by owen200008** [comment]
> > use dubbo.application.metadata-service-port=31052 ?
> 
> After apply this PR?

i support throw exception when no config the metadata-service-port， not use the default or hide

**Review by chickenlj — APPROVED** [review]

File: dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java (hunk 1 above)
Comment (chickenlj) [reply dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java:125]: I will submit a followup patch right away regarding this small issue.
