### PR TITLE
bugfix: meatadata service support read dubbo:protocol

### LINKED ISSUE #10826: Unable to change serialization type of MetadataService
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.1
* Operating System version: macosx
* Java version: 17

### Steps to reproduce this issue
provider:
```
    <dubbo:protocol name="dubbo" serialization="fastjson2" port="20880"></dubbo:protocol>
    <dubbo:service protocol="dubbo" serialization="fastjson2" version="${dubbo.version:3.1.1}" loadbalance="roundrobin" interface="cn.app.service.TestService" timeout="50" registry="dubboRegistry"
                   ref="testService"/>
```
consumer:
The serialization method remains the same as hesian2
image
image

Self-declared dubbo interfaces are normal
image

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

### PR DESCRIPTION
**Pull request by a364176773**
## What is the purpose of the change
fixes #10826

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

File: dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java [hunk 1]
```diff
@@ -113,7 +117,8 @@ private ProtocolConfig generateMetadataProtocol() {
 
         ProtocolConfig protocolConfig = new ProtocolConfig();
         protocolConfig.setName(specifiedProtocol);
-
+        String serialization = getSerialization(specifiedProtocol);
+        protocolConfig.setSerialization(serialization);
```
Comment (AlbumenJ) [inline dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java:121]: Maybe we can merge all of the config from exist protocol config, or directly reuse(if user do not specify different port).

Comment (AlbumenJ) [inline dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java:121]: BTW, please add some uts to verify this

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

File: dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java (hunk 1 above)
Comment (a364176773) [reply dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java:121]: > BTW, please add some uts to verify this

We should do this, but need to establish a priority for the configuration reads

File: dubbo-common/src/main/java/org/apache/dubbo/config/ProtocolConfig.java [hunk 2]
```diff
@@ -579,4 +582,28 @@ public String getExtProtocol() {
     public void setExtProtocol(String extProtocol) {
         this.extProtocol = extProtocol;
     }
+
+    public void mergeProtocol(ProtocolConfig protocolConfig) {
```
Comment (AlbumenJ) [inline dubbo-common/src/main/java/org/apache/dubbo/config/ProtocolConfig.java:586]: add some unit test cases for this

File: dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java [hunk 3]
```diff
@@ -146,6 +145,9 @@ private ProtocolConfig generateMetadataProtocol() {
         } else {
             protocolConfig.setPort(port);
         }
+        
+        applicationModel.getApplicationConfigManager().getProtocol(specifiedProtocol)
+            .ifPresent(protocolConfig::mergeProtocol);
```
Comment (AlbumenJ) [inline dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java:150]: Will this override `port` configuration?

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

File: dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java (hunk 3 above)
Comment (a364176773) [reply dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java:150]: > Will this override `port` configuration?

No, it will only work on variables with null values

File: dubbo-common/src/main/java/org/apache/dubbo/config/ProtocolConfig.java (hunk 2 above)
Comment (a364176773) [reply dubbo-common/src/main/java/org/apache/dubbo/config/ProtocolConfig.java:586]: done

**Review by AlbumenJ — APPROVED** [review]
LGTM
