### PR TITLE
[3.0] fix urlInvokerMap concurrent access issue

### LINKED ISSUE #8675: [3.0] ServiceDiscoveryRegistryDirectory的refreshInvoker方法和isAvailable存在并行执行冲突
### Environment

* Dubbo version: 3.0
集成构建时，执行GenericServiceTest测试方法下面的语句时，
```
        // Test generic service without interface class locally
        result = genericServiceWithoutInterfaceRef.$invoke("sayHello", new String[]{"java.lang.String"}, new Object[]{"generic"});
```
ReferenceConfig的checkInvokerAvailable方法有时会抛异常，导致集成构建失败，异常信息如下：
java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.config.spring.api.LocalMissClass. No provider available for the service org.apache.dubbo.config.spring.api.LocalMissClass from the url dubbo://10.1.0.184/org.apache.dubbo.config.spring.api.LocalMissClass?application=dubbo-generic-consumer&dubbo=2.0.2&file.cache=false&generic=true&init=false&interface=org.apache.dubbo.config.spring.api.LocalMissClass&metadata-type=remote&pid=9816&register.ip=10.1.0.184&release=3.0.3-SNAPSHOT&side=consumer&sticky=false&timestamp=1630699707283 to the consumer 10.1.0.184 use dubbo version 3.0.3-SNAPSHOT
	at org.apache.dubbo.config.spring.schema.GenericServiceTest.testGeneric(GenericServiceTest.java:97)

* 更新2021-09-10：
执行ServiceDiscoveryRegistryDirectory的refreshInvoker方法刷新urlInvokerMap的线程和执行ReferenceConfig的init方法的线程不是一个线程，刷新的线程名是main-EventThread，执行init的线程是main线程。而refreshInvoker方法调用toInvokers时会先把当前的this.urlInvokerMap里面的entry全清，在将newUrlInvokerMap重新赋值给this.urlInvokerMap前，如果恰好遇到执行init的main线程在执行isAvailable判断就会因为this.urlInvokerMap没有entry而返回false。
重现方法：在ServiceDiscoveryRegistryDirectory的toInvokers方法调用返回的下一行代码设置断点，在isAvailable的Map<String, Invoker<T>> localUrlInvokerMap = urlInvokerMap处设置断点，执行到toInvokers返回时暂停main-EventThread线程执行，切换到停留在isAvailable的main线程继续执行，就能重现这个issue。

PS：
采用genericServiceWithoutInterface方式的JavaConfigReferenceBeanTest的testGenericServiceAnnotationBean方法的165行有时也抛异常
* 更新2021-09-10：这个RpcException异常可能是上一个测试方法执行AfterEach释放了全局资源干扰了仍在运行的dubbo后台线程导致的，已另开issue
```
        Object sayHelloResult = genericServiceWithoutInterface.$invoke("sayHello", new String[]{"java.lang.String"}, new Object[]{"Dubbo"});
```
只是抛的异常是RpcException: Directory already destroyed
```
2021-09-03T18:39:04.9792146Z org.apache.dubbo.rpc.RpcException: Directory already destroyed .url: zookeeper://127.0.0.1:2181/org.apache.dubbo.registry.RegistryService?application=consumer-app&dubbo=2.0.2&file.cache=false&pid=8884&release=3.0.3-SNAPSHOT&timestamp=1630694303313
2021-09-03T18:39:04.9797067Z 	at org.apache.dubbo.config.spring.reference.javaconfig.JavaConfigReferenceBeanTest.testGenericServiceAnnotationBean(JavaConfigReferenceBeanTest.java:165)
```

### PR DESCRIPTION
**Pull request by zrlw**
## What is the purpose of the change
fix #8675
it might cause chaos that main thread does isAvailable() while main-EventThread does refreshInvoker() if both of them operate urlInvokerMap directly, especially while main-EventThread gets empty url lists to refresh.

github integration test log snippet:
```
<=== urlInvokerMap will be removed at refreshInvoker() in ServiceDiscoveryRegistryDirectory
[20/09/21 10:06:14:014 UTC] main-EventThread  INFO client.ServiceDiscoveryRegistryDirectory:  [DUBBO] Refreshed invoker size 1, dubbo version: 3.0.3-SNAPSHOT, current host: 172.26.0.3 
...
<=== IllegalStateException will be trigged if urlInvokerMap is empty at checkInvokerAvailable() in ReferenceConfig
[20/09/21 10:06:14:014 UTC] main ERROR deploy.DefaultModuleDeployer:  [DUBBO] Dubbo Module[1.1.1] refer catch error, dubbo version: 3.0.3-SNAPSHOT, current host: 172.26.0.3
java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.samples.async.api.GreetingService. No provider available for the service org.apache.dubbo.samples.async.api.GreetingService from the url dubbo://172.26.0.3/org.apache.dubbo.samples.async.api.GreetingService?application=async-consumer&dubbo=2.0.2&interface=org.apache.dubbo.samples.async.api.GreetingService&metadata-type=remote&methods=greeting,replyGreeting&pid=17&register.ip=172.26.0.3&release=3.0.3-SNAPSHOT&side=consumer&sticky=false&timeout=10000&timestamp=1632132372838 to the consumer 172.26.0.3 use dubbo version 3.0.3-SNAPSHOT
	at org.apache.dubbo.config.ReferenceConfig.checkInvokerAvailable(ReferenceConfig.java:520)
```

### CODE REVIEW

**Comment by pinxiong** [comment]
Could you provide more detailed info? And why did you add a new variable `forbidden`?

**Comment by zrlw** [comment]
> Could you provide more detailed info? And why did you use the variable `forbidden`?
when main-EventThread does refreshInvoker() by empty url list received, main thread does isAvaliable() concurrently.it might cause chaos.
just like isAvaliable() of RegistryDirectory in master branch.
pls see more details in #8675

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java [hunk 1]
```diff
@@ -246,12 +246,17 @@ private void refreshInvoker(List<URL> invokerUrls) {
...
-            Map<String, Invoker<T>> oldUrlInvokerMap = this.urlInvokerMap; // local reference
             if (CollectionUtils.isEmpty(invokerUrls)) {
                 return;
             }
 
-            Map<String, Invoker<T>> newUrlInvokerMap = toInvokers(invokerUrls);// Translate url list to Invoker map
+            // can't use local reference because this.urlInvokerMap might be accessed at isAvailable() by main thread concurrently.
+            Map<String, Invoker<T>> oldUrlInvokerMap = null;
+            if (this.urlInvokerMap != null) {
+                oldUrlInvokerMap = new HashMap<>();
```
Comment (AlbumenJ) [inline dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java:256]: it would be better to sepcify the default size for HashMap here

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java [hunk 2]
```diff
@@ -216,7 +216,14 @@ private void refreshInvoker(List<URL> invokerUrls) {
             if (invokerUrls.isEmpty()) {
                 return;
             }
-            Map<URL, Invoker<T>> newUrlInvokerMap = toInvokers(invokerUrls);// Translate url list to Invoker map
+            
+            // can't use local reference because this.urlInvokerMap might be accessed at isAvailable() by main thread concurrently.
+            Map<URL, Invoker<T>> oldUrlInvokerMap = null;
+            if (this.urlInvokerMap != null) {
+                oldUrlInvokerMap = new HashMap<>();
```
Comment (AlbumenJ) [inline dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java:223]: also for there

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java (hunk 1 above)
Comment (AlbumenJ) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java:256]: using LinkedHashMap will reduce temporally memery usage when using iterator in forEach

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java (hunk 2 above)
Comment (zrlw) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java]: pls review again

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java (hunk 1 above)
Comment (zrlw) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java]: @AlbumenJ already changed to LinkedHashMap and set the default size

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java [hunk 3]
```diff
@@ -222,7 +223,14 @@ private void refreshInvoker(List<URL> invokerUrls) {
             if (invokerUrls.isEmpty()) {
                 return;
             }
-            Map<URL, Invoker<T>> newUrlInvokerMap = toInvokers(invokerUrls);// Translate url list to Invoker map
+            
+            // can't use local reference because this.urlInvokerMap might be accessed at isAvailable() by main thread concurrently.
+            Map<URL, Invoker<T>> oldUrlInvokerMap = null;
+            if (this.urlInvokerMap != null) {
+                oldUrlInvokerMap = new LinkedHashMap<>(this.urlInvokerMap.size());
```
Comment (AlbumenJ) [inline dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java:230]: Please consider load factor. `this.urlInvokerMap.size() / 0.75f + 1` would reduce one time resize.

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java (hunk 3 above)
Comment (zrlw) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java:230]: do you mean setting the initial capacity greater than the maximum number of entries divided by the load factor (default: 0.75) to avoid rehash operations?

Comment (zrlw) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java:230]:
```
            if (this.urlInvokerMap != null) {
                // the initial capacity should be set greater than the maximum number of entries divided by the load factor to avoid resizing.
                oldUrlInvokerMap = new LinkedHashMap<>(Math.round(1 + this.urlInvokerMap.size() / DEFAULT_LOAD_FACTOR));
                this.urlInvokerMap.forEach(oldUrlInvokerMap::put);
            }
```
pls review again

**Review by AlbumenJ — APPROVED** [review]
