### PR TITLE
[3.0] fix #10042, ignore overlapping lock exception and print log

### LINKED ISSUE #10042: 启动服务总是打印警告信息的堆栈异常
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.7
* Operating System version: windows+linux
* Java version:  8  11

### Steps to reproduce this issue

1. 启动进程
2. 打印warn异常堆栈

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

警告信息里面打印了一个堆栈异常看起来很奇怪

### Actual Behavior

If there is an exception, please attach the exception trace:
不要打印异常堆栈

```
Just put your stack trace here!
java.nio.channels.OverlappingFileLockException: null 
          at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255) ~[?:1.8.0_121] 
          at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152) ~[?:1.8.0_121] 
          at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108) ~[?:1.8.0_121] 
          at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155) ~[?:1.8.0_121] 
          at org.apache.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:192) ~[dubbo-3.0.7.jar!/:3.0.7]
```

### PR DESCRIPTION
**Pull request by wangchengming666**
fix #10042

### CODE REVIEW

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java [hunk 1]
```diff
@@ -220,16 +221,17 @@ public void doSaveProperties(long version) {
...
-            if (savePropertiesRetryTimes.get() >= MAX_RETRY_TIMES_SAVE_PROPERTIES) {
+            } catch (Throwable e) {
                 if (e instanceof OverlappingFileLockException) {
-                    // fix #9341, ignore OverlappingFileLockException
                     logger.info("Failed to save registry cache file for file overlapping lock exception, file name " + file.getName());
                 } else {
-                    logger.warn("Failed to save registry cache file after retrying " + MAX_RETRY_TIMES_SAVE_PROPERTIES + " times, cause: " + e.getMessage(), e);
+                    throw e;
                 }
+            }
```
Comment (CrazyHZM) [inline dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java:230]: `OverlappingFileLockException` still needs to be retried.

**Review by CrazyHZM — CHANGES_REQUESTED** [review]

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java (hunk 1 above)
Comment (wangchengming666) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java]: Thanks for your review

**Review by CrazyHZM — APPROVED** [review]
