### PR TITLE
[Dubbo-4694] Fix consumer can't return quickly, when the provider interrupts abnormally #4694

### LINKED ISSUE #4694: When the provider interrupts abnormally, the consumer cannot return quickly and still waits for the timeout to end
- [√] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: Windows 10
* Java version: Oracle JDK 1.8

### Steps to reproduce this issue

1. set @Reference(timeout = 10000)
2. kill -9 provider

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

fast return when timeout is not reached

### Actual Result

What actually happens?

the consumer returns until the timeout ends

detail see #1968

### PR DESCRIPTION
**Pull request by zhaozhiwei2017**
## What is the purpose of the change

1. run provider
2. debug consumer
3. let the provider offline in registry center
4. in consumer, just org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeChannel#close() get called

fix #4694 

## Brief changelog

consumer return quickly, when the provider interrupts abnormally

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily:

- [√] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [√] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

File: dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeChannel.java [hunk 1]
```diff
@@ -1,251 +1,252 @@
...
+
+    @Override
+    public boolean isClosed() {
+        return closed;
+    }
+
+    @Override
+    public void close() {
+        try {
+            DefaultFuture.closeChannel(channel);
```
Comment (zhaozhiwei2017) [inline dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeChannel.java]: just added this row

**Comment by beiwei30** [comment]
@zhaozhiwei2017 have you verified on the master branch, this solution doesn't work. Would you mind take a look at #4700?

**Comment by zhaozhiwei2017** [comment]
> @zhaozhiwei2017 have you verified on the master branch, this solution doesn't work. Would you mind take a look at #4700?

I verified that the master branch works, and I debug the code, channel are all NettyClient.
see.
image

**Comment by beiwei30** [comment]
> > @zhaozhiwei2017 have you verified on the master branch, this solution doesn't work. Would you mind take a look at #4700?
> 
> I verified that the master branch works, and I debug the code, channel are all NettyClient.
> see.
> image

This is quite strange, I will ask someone else to verify it too.

**Comment by zhaozhiwei2017** [comment]
> > > @zhaozhiwei2017 have you verified on the master branch, this solution doesn't work. Would you mind take a look at #4700?
> > 
> > 
> > I verified that the master branch works, and I debug the code, channel are all NettyClient.
> > see.
> > image
> 
> This is quite strange, I will ask someone else to verify it too.

I looked at the source code in org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeChannel#request(java.lang.Object, int), DefaultFuture is created in this method, and the HeaderExchangeChannel channel is set to the CHANNELS property of DefaultFuture
```
    //  org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeChannel#request(java.lang.Object, int)
    @Override
    public CompletableFuture<Object> request(Object request, int timeout) throws RemotingException {
        if (closed) {
            throw new RemotingException(this.getLocalAddress(), null, "Failed to send request " + request + ", cause: The channel " + this + " is closed!");
        }
        // create request.
        Request req = new Request();
        req.setVersion(Version.getProtocolVersion());
        req.setTwoWay(true);
        req.setData(request);
        DefaultFuture future = DefaultFuture.newFuture(channel, req, timeout);
        try {
            channel.send(req);
        } catch (RemotingException e) {
            future.cancel();
            throw e;
        }
        return future;
    }

    // org.apache.dubbo.remoting.exchange.support.DefaultFuture#newFuture
    public static DefaultFuture newFuture(Channel channel, Request request, int timeout) {
        final DefaultFuture future = new DefaultFuture(channel, request, timeout);
        // timeout check
        timeoutCheck(future);
        return future;
    }

    // org.apache.dubbo.remoting.exchange.support.DefaultFuture#DefaultFuture
    private DefaultFuture(Channel channel, Request request, int timeout) {
        this.channel = channel;
        this.request = request;
        this.id = request.getId();
        this.timeout = timeout > 0 ? timeout : channel.getUrl().getPositiveParameter(TIMEOUT_KEY, DEFAULT_TIMEOUT);
        // put into waiting map.
        FUTURES.put(id, this);
        CHANNELS.put(id, channel);
    }
```

**Comment by cvictory** [comment]
I have a test on your modification. And I find no matter what your code is added, `org.apache.dubbo.remoting.exchange.support.DefaultFuture#closeChannel` will be invoked by `org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler#disconnected` .

The key of this issue is https://github.com/apache/dubbo/issues/4699,  the equals don't take effective.

**Comment by zhaozhiwei2017** [comment]
I think we're not talking about a problem, my question is when the provider abnormal disconnect, the provider will not send TCP FIN requests at this moment, but the registry would perceive the provider has been disconnected, then `org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler#disconnected` will not be calling, `org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeChannel#close` will be invoked

**Comment by beiwei30** [comment]
@zhaozhiwei2017 this is quite strange, what I observed (and @cvictory verified) on the main trunk is one instance is NettyChannel, and the other is NettyClient. Would you mind to drop a sample app on github to reproduce what you observed?

**Comment by zhaozhiwei2017** [comment]
> @zhaozhiwei2017 this is quite strange, what I observed (and @cvictory verified) on the main trunk is one instance is NettyChannel, and the other is NettyClient. Would you mind to drop a sample app on github to reproduce what you observed?

pls. see my last comment

**Comment by carryxyh** [comment]
I think his pr is meaningful. As I said in the comment [here](https://github.com/apache/dubbo/issues/1968#issuecomment-515899985). 

We should consider that if the provider is abnormally disconnected (powered off, disconnected), we should also let the pending request return.

**Comment by cvictory** [comment]
The DefaultFuture.closeChannel(channel) will be invoked by the code of @zhaozhiwei2017 .

Firstly I think it is unmeaning , but i check it again and find it will invoked DefaultFuture.closeChannel with NettyClient.

image

So I think it has the same effective with https://github.com/apache/dubbo/pull/4700/files

**Comment by zhaozhiwei2017** [comment]
I think our two pr solved different problems. His solved the normal shutdown of the provider, while mine solved the abnormal shutdown of the provider

**Comment by cvictory** [comment]
I do the test as follow:
1. run provider
2.debug consumer
3. `kill -9 pid`    --pid is from provider
4.  In consumer, org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler#disconnected will be invoked firstly, then HeaderExchangeChannel#close will be invoked.

**Comment by zhaozhiwei2017** [comment]
Sorry I didn't express myself clearly.
I used the registry offline provider to simulate the provider abnormal shutdown.

I do the test as follow:

1. run provider
2. debug consumer
3. let the provider offline in registry center
4. in consumer, just `org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeChannel#close()` get called

**Comment by cvictory** [comment]
@zhaozhiwei2017  There some build failed. Could you fix the problem?

**Comment by beiwei30** [comment]
> I think his pr is meaningful. As I said in the comment [here](https://github.com/apache/dubbo/issues/1968#issuecomment-515899985).
> 
> We should consider that if the provider is abnormally disconnected (powered off, disconnected), we should also let the pending request return.

I almost agree with @carryxyh 's opinion that it would make dubbo more robust if we add `DefaultFuture.closeChannel(channel)` in the close() method after go through the whole discussion again.

**Comment by cvictory** [comment]
HeaderExchangeChannel.close will be invoked when zookeeper data is changed. (One provider is disapper)

```
close:134, HeaderExchangeChannel {org.apache.dubbo.remoting.exchange.support.header}
close:158, HeaderExchangeChannel {org.apache.dubbo.remoting.exchange.support.header}
close:133, HeaderExchangeClient {org.apache.dubbo.remoting.exchange.support.header}
close:153, ReferenceCountExchangeClient {org.apache.dubbo.rpc.protocol.dubbo}
destroy:144, DubboInvoker {org.apache.dubbo.rpc.protocol.dubbo}
destroy:85, AsyncToSyncInvoker {org.apache.dubbo.rpc.protocol}
destroy:89, ListenerInvokerWrapper {org.apache.dubbo.rpc.listener}
destroy:98, ProtocolFilterWrapper$1 {org.apache.dubbo.rpc.protocol}
destroy:197, ProtocolFilterWrapper$CallbackRegistrationInvoker {org.apache.dubbo.rpc.protocol}
destroy:61, InvokerWrapper {org.apache.dubbo.rpc.protocol}
destroyAllInvokers:506, RegistryDirectory {org.apache.dubbo.registry.integration}
refreshInvoker:264, RegistryDirectory {org.apache.dubbo.registry.integration}
refreshOverrideAndInvoker:239, RegistryDirectory {org.apache.dubbo.registry.integration}
notify:233, RegistryDirectory {org.apache.dubbo.registry.integration}
notify:418, AbstractRegistry {org.apache.dubbo.registry.support}
doNotify:369, FailbackRegistry {org.apache.dubbo.registry.support}
notify:360, FailbackRegistry {org.apache.dubbo.registry.support}
lambda$doSubscribe$2:174, ZookeeperRegistry {org.apache.dubbo.registry.zookeeper}
childChanged:-1, 1617937669 {org.apache.dubbo.registry.zookeeper.ZookeeperRegistry$$Lambda$51}
process:282, CuratorZookeeperClient$CuratorWatcherImpl {org.apache.dubbo.remoting.zookeeper.curator}
process:83, NamespaceWatcher {org.apache.curator.framework.imps}
processEvent:533, ClientCnxn$EventThread {org.apache.zookeeper}
run:508, ClientCnxn$EventThread {org.apache.zookeeper}
```
The org.apache.dubbo.remoting.transport.dispatcher.all.AllChannelHandler#disconnected is invoked by org.apache.dubbo.remoting.transport.dispatcher.all.AllChannelHandler#disconnected.

And NettyClientHandler is extend netty ChannelInboundHandler and ChannelOutboundHandler. So when the connection between client and server is lost, NettyClientHandler will be invoked.
-------
And it is also when 
```
"NettyClientWorker-4-1"@3,246 in group "main": RUNNING
disconnected:53, AllChannelHandler {org.apache.dubbo.remoting.transport.dispatcher.all}
disconnected:53, HeartbeatHandler {org.apache.dubbo.remoting.exchange.support.header}
disconnected:48, AbstractChannelHandlerDelegate {org.apache.dubbo.remoting.transport}
disconnected:131, AbstractPeer {org.apache.dubbo.remoting.transport}
channelInactive:69, NettyClientHandler {org.apache.dubbo.remoting.transport.netty4}
invokeChannelInactive:245, AbstractChannelHandlerContext {io.netty.channel}
invokeChannelInactive:231, AbstractChannelHandlerContext {io.netty.channel}
fireChannelInactive:224, AbstractChannelHandlerContext {io.netty.channel}
channelInactive:75, ChannelInboundHandlerAdapter {io.netty.channel}
channelInactive:277, IdleStateHandler {io.netty.handler.timeout}
invokeChannelInactive:245, AbstractChannelHandlerContext {io.netty.channel}
invokeChannelInactive:231, AbstractChannelHandlerContext {io.netty.channel}
fireChannelInactive:224, AbstractChannelHandlerContext {io.netty.channel}
channelInputClosed:377, ByteToMessageDecoder {io.netty.handler.codec}
channelInactive:342, ByteToMessageDecoder {io.netty.handler.codec}
invokeChannelInactive:245, AbstractChannelHandlerContext {io.netty.channel}
invokeChannelInactive:231, AbstractChannelHandlerContext {io.netty.channel}
fireChannelInactive:224, AbstractChannelHandlerContext {io.netty.channel}
channelInactive:1429, DefaultChannelPipeline$HeadContext {io.netty.channel}
invokeChannelInactive:245, AbstractChannelHandlerContext {io.netty.channel}
invokeChannelInactive:231, AbstractChannelHandlerContext {io.netty.channel}
fireChannelInactive:947, DefaultChannelPipeline {io.netty.channel}
run:822, AbstractChannel$AbstractUnsafe$8 {io.netty.channel}
safeExecute$$$capture:163, AbstractEventExecutor {io.netty.util.concurrent}
safeExecute:-1, AbstractEventExecutor {io.netty.util.concurrent}
runAllTasks:404, SingleThreadEventExecutor {io.netty.util.concurrent}
run:465, NioEventLoop {io.netty.channel.nio}
run:884, SingleThreadEventExecutor$5 {io.netty.util.concurrent}
run:30, FastThreadLocalRunnable {io.netty.util.concurrent}
run:748, Thread {java.lang}
```
总结下：
org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler#disconnected 被用于监听server端的连接
 HeaderExchangeChannel#close 用于监听注册中心的连接，当有provider下线时，会调用close。

所以两个都是有意义的。

**Comment by cvictory** [comment]
@zhaozhiwei2017  能看下文件吗？ 这样很难看到修改点，麻烦去掉一些特殊字符。

**Comment by zhaozhiwei2017** [comment]
> @zhaozhiwei2017 能看下文件吗？ 这样很难看到修改点，麻烦去掉一些特殊字符。

好的，稍等

**Comment by zhaozhiwei2017** [comment]
@cvictory   Hi, I formatted my code
