### PR TITLE
[Dubbo] Fixed IndexOutOfBoundsException in base642bytes(String, int, int, char[])

### LINKED ISSUE #4514: Calling base642bytes(String, char[]) can throw an unexpected IndexOutOfBoundsException
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.2
* Operating System version: Ubuntu 18.04
* Java version: 1.8

### Steps to reproduce this issue

Call `base642bytes(String, char[])` with a random `String` and `C64.toCharArray()`.

```
import org.apache.dubbo.common.io.Bytes;

public class Testing {

  private static final String C64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";

  public static void main(String[] args) {
    Bytes.base642bytes("ZHViYm8=", C64.toCharArray());
  }
}
```

### Expected Result

No crash.

### Actual Result

What actually happens?

`IndexOutOfBoundsException`

Stack trace:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 5
	at org.apache.dubbo.common.io.Bytes.base642bytes(Bytes.java:752)
	at org.apache.dubbo.common.io.Bytes.base642bytes(Bytes.java:692)
	at Testing.main(Testing.java:8)
```

### PR DESCRIPTION
**Pull request by Maxi17**
## What is the purpose of the change

Fixes #4514

## Brief changelog

This change fixes `Bytes.base642bytes(String, int, int, char[])` by adjusting `num` and `rem` variables when required, similar to `Bytes.base642bytes(String, int, int, String)`.

## Verifying this change

A new test case was added in `BytesTest.java`

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

File: dubbo-common/src/main/java/org/apache/dubbo/common/io/Bytes.java [hunk 1]
```diff
@@ -730,8 +730,12 @@ public static String bytes2base64(final byte[] bs, final int off, final int len,
             char pc = code[64];
             if (str.charAt(off + len - 2) == pc) {
                 size -= 2;
+                --num;
```
Comment (beiwei30) [inline dubbo-common/src/main/java/org/apache/dubbo/common/io/Bytes.java]: it looks like we can unify the logic for method *public static byte[] base642bytes(final String str, final int off, final int len, final String code)* and method *public static byte[] base642bytes(final String str, final int off, final int len, final char[] code) *

would you mind to give it a try?

**Comment by beiwei30** [comment]
I will merge and follow up the code cleanup.
