### PR TITLE
[master] fix destroy IllegalStateException and doOverrideIfNecessary NPE

### LINKED ISSUE #8681: github构建日志里有很多涉及RegistryProtocol的异常
### Environment

* Dubbo version: 3.0

### Steps to reproduce this issue
翻看github构建日志本来是去找GenericServiceTest为啥常常出现java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.config.spring.api.LocalMissClass的线索，相关的线索没找到，却找到了这个
2021-09-04T20:19:48.3933128Z [04/09/21 20:19:47:427 UTC] main  WARN integration.RegistryProtocol:  [DUBBO] unsubscribe listener == null, dubbo version: 3.0.3-SNAPSHOT, current host: 172.17.16.1
2021-09-04T20:19:48.3934495Z java.lang.IllegalArgumentException: unsubscribe listener == null
2021-09-04T20:19:48.3936385Z 	at org.apache.dubbo.registry.support.AbstractRegistry.unsubscribe(AbstractRegistry.java:329)
2021-09-04T20:19:48.3938947Z 	at org.apache.dubbo.registry.support.FailbackRegistry.unsubscribe(FailbackRegistry.java:328)
2021-09-04T20:19:48.3942540Z 	at org.apache.dubbo.registry.ListenerRegistryWrapper.unsubscribe(ListenerRegistryWrapper.java:134)
2021-09-04T20:19:48.3945186Z 	at org.apache.dubbo.registry.integration.RegistryProtocol$ExporterChangeableWrapper.unexport(RegistryProtocol.java:876)
2021-09-04T20:19:48.3948433Z 	at org.apache.dubbo.registry.integration.RegistryProtocol$DestroyableExporter.unexport(RegistryProtocol.java:669)
2021-09-04T20:19:48.3950662Z 	at org.apache.dubbo.config.ServiceConfig.unexport(ServiceConfig.java:187)
2021-09-04T20:19:48.3952706Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.lambda$unexportServices$9(DubboBootstrap.java:1487)
2021-09-04T20:19:48.3954404Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2021-09-04T20:19:48.3956255Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.unexportServices(DubboBootstrap.java:1484)
2021-09-04T20:19:48.3958714Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.destroy(DubboBootstrap.java:1635)
2021-09-04T20:19:48.3960885Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.reset(DubboBootstrap.java:239)
2021-09-04T20:19:48.3963018Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.reset(DubboBootstrap.java:225)
2021-09-04T20:19:48.3965492Z 	at org.apache.dubbo.config.spring.schema.GenericServiceTest.tearDown(GenericServiceTest.java:67)
并且不止这一个测试类抛这个异常，有十多个测试类都抛这个东西，看了看代码，感觉应该是重复注销导致的，RegistryProtocol注销listener前检查一下是否为null应该就能避免这个异常了。

### PR DESCRIPTION
**Pull request by zrlw**
## What is the purpose of the change
fix #8681 on master

### CODE REVIEW

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java [hunk 1]
```diff
@@ -688,7 +693,8 @@ public synchronized void doOverrideIfNecessary() {
                 return;
             }
             //The current, may have been merged many times
-            URL currentUrl = exporter.getInvoker().getUrl();
+            Invoker<?> exporterInvoker = exporter.getInvoker();
```
Comment (AlbumenJ) [inline dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java:696]: exporterInvoker should not be null here when calling `doOverrideIfNecessary`

Comment (zrlw) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java:696]: one report of github say NPE here

Comment (zrlw) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java:696]: 属于偶发异常，可能和 #8725 是同样的问题，AfterEach的释放全局资源操作干扰了正在运行的dubbo后台线程，导致后续的测试方法出现异常。

Comment (zrlw) [reply dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java:696]: in branch 3.0, ReferenceConfigTest testReferenceRetry()  uses InjvmProtocol.getInjvmProtocol().export(...) instead of  sc.export(), it doesn't call RegistryProtocol.doOverrideIfNecessary at all, so 3.0 might also have the same issue.
