### PR TITLE
[3.0]fix #9341, ignore OverlappingFileLockException

### LINKED ISSUE #9341: dubbo-3.0.4，多线程操作dubbo-cache-file导致`java.nio.channels.OverlappingFileLockException`
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.4
* Operating System version: win10
* Java version: jdk8

### Steps to reproduce this issue

1. dubbo-samples 项目中的：<https://github.com/apache/dubbo-samples/blob/b4c7fd7ef813515f59181ef16584319efc6fb738/dubbo-samples-zookeeper/src/test/java/org/apache/dubbo/samples/GreetingServiceIT.java#L41-L41>

2. 适当延长 持有dubbo-cache-file 锁的时间
`org.apache.dubbo.registry.support.AbstractRegistry#doSaveProperties` 第187行附近。
image

备注：
```
// 3.0.4之前的版本，只是单线程操作 dubbo-cache-file
registryCacheExecutor = Executors.newFixedThreadPool(1, new NamedThreadFactory("DubboSaveRegistryCache", true));

// dubbo-3.0.4，实现方式变更
registryCacheExecutor = url.getOrDefaultApplicationModel().getDefaultExtension(ExecutorRepository.class).getSharedExecutor();
```

实际项目中大约 `AbstractRegistry#lastCacheChanged`被递增到 150左右，普遍出现10次以上的`OverlappingFileLockException `。

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

不要出现`OverlappingFileLockException`，并且打印过多的error日志。

### Actual Behavior

频繁打印错误日志

If there is an exception, please attach the exception trace:

```
 [Dubbo-shared-handler-thread-1] [WARN ]  [DUBBO] Failed to save registry cache file after retrying 3 times, cause: null, dubbo version: 3.0.4, current host: ......... - o.a.d.r.zookeeper.ZookeeperRegistry:205
java.nio.channels.OverlappingFileLockException: null
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1154)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1165)
	at org.apache.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:186)
	at org.apache.dubbo.registry.support.AbstractRegistry$SaveProperties.run(AbstractRegistry.java:541)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### PR DESCRIPTION
**Pull request by wangchengming666**
see https://www.runoob.com/manual/jdk11api/java.base/java/nio/channels/OverlappingFileLockException.html

### CODE REVIEW

File: dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java [hunk 1]
```diff
@@ -203,7 +204,11 @@ public void doSaveProperties(long version) {
         } catch (Throwable e) {
             savePropertiesRetryTimes.incrementAndGet();
             if (savePropertiesRetryTimes.get() >= MAX_RETRY_TIMES_SAVE_PROPERTIES) {
-                logger.warn("Failed to save registry cache file after retrying " + MAX_RETRY_TIMES_SAVE_PROPERTIES + " times, cause: " + e.getMessage(), e);
+                if (e instanceof OverlappingFileLockException) {
+                    // fix #9341, ignore OverlappingFileLockException
```
Comment (chickenlj) [inline dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java:208]: Adding one short info log here would be better for the users to notice what has happened.

**Review by chickenlj — CHANGES_REQUESTED** [review]
