### PR TITLE
[3.0] Clear up env when destroy

### LINKED ISSUE #10192: Potential memory leak risk in ReferenceConfig
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

ReferenceConfig throw IllegalStateException when check failed, but consumerModel is still registered.

### PR DESCRIPTION
**Pull request by AlbumenJ**
## What is the purpose of the change
Fix #10192

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

File: dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java [hunk 1]
```diff
@@ -532,17 +532,34 @@ private void createInvokerForRemote() {
...
-                + interfaceName
-                + ". No provider available for the service "
-                + (group == null ? "" : group + "/")
-                + interfaceName +
-                (version == null ? "" : ":" + version)
-                + " from the url "
-                + invoker.getUrl()
-                + " to the consumer "
-                + NetUtils.getLocalHost() + " use dubbo version " + Version.getVersion());
+            try {
```
Comment (guohao) [inline dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java:535]: It is better to adopt a more general-purpose mechanism to manage `ReferenceConfig`'s lifecycle in avoid of other `Exception` s or rollbacks may occur during initializing phase. Not only `checkAvailable()`

Comment (guohao) [reply dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java:535]: Other resources created and shared by `Config`s may also be took into consideration.
- Service Discovery: Instance subscriptions/ URLs 
- Network IO. Netty's EventLoop/ Timer/ Connections.
- Caches

**Review by guohao — APPROVED** [review]
LGTM
