### PR TITLE
fix issue: get available protocol for metadata service.

### LINKED ISSUE #10823: Enhance protocol order in MetadataServiceExporter
> 这里没指定 metadata 协议 port 的时候 是使用用户指定的应用协议呢？ 还是保持现在的 默认使用dubbo 但是 优化下 错误 提示

这里最好将默认值改成从用户环境中获取已经配置的额 protocol，都没配置再使用 dubbo

_Originally posted by @AlbumenJ in https://github.com/apache/dubbo/issues/10795#issuecomment-1289913950_

### PR DESCRIPTION
**Pull request by pandaapo**
## What is the purpose of the change
Fixes #10823

## Brief changelog
When there is no specific protocol for metadata service, get available protocol from environment before using default.

## Verifying this change
Configure a dubbo application like:
```
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: tri # or other valid protocol
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
```
There will be no `java.util.NoSuchElementException` thrown in `ConfigurableMetadataServiceExporter.getProtocolConfig(String)` when start this application.

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

File: dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java [hunk 1]
```diff
@@ -175,10 +177,75 @@ private String getSpecifiedProtocol() {
...
+
+    /**
+     * Get other configured protocol from environment in priority order. If get nothing, use default dubbo.
+     *
+     * @return
+     */
+    private String getRelatedOrDefaultProtocol() {
+        String protocol = "";
+        // <dubbo:consumer/>
+        Collection<ConsumerConfig> consumers = applicationModel.getDefaultModule().getConfigManager().getConsumers();
```
Comment (AlbumenJ) [inline dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java:195]: read all modules (except internal  module)

File: dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java [hunk 2]
```diff
@@ -175,10 +177,75 @@ private String getSpecifiedProtocol() {
...
+                                }
+                            }
+                        }
+                    }
+                }
+            }
+        }
+        // <dubbo:protocol/>
+        if (StringUtils.isEmpty(protocol)) {
+            Collection<ProtocolConfig> protocols = applicationModel.getDefaultModule().getConfigManager().getProtocols();
```
Comment (AlbumenJ) [inline dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java:229]:
```suggestion
            Collection<ProtocolConfig> protocols = applicationModel.getApplicationConfigManager().getProtocols();
```

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

File: dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java [hunk 3]
```diff
@@ -175,10 +178,82 @@ private String getSpecifiedProtocol() {
...
+    /**
+     * Get other configured protocol from environment in priority order. If get nothing, use default dubbo.
+     *
+     * @return
+     */
+    private String getRelatedOrDefaultProtocol() {
+        String protocol = "";
+        // <dubbo:consumer/>
+        List<ModuleModel> moduleModels = applicationModel.getPubModuleModels();
+        breakPoint:
```
Comment (AlbumenJ) [inline dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java:197]: Do not use `breakPoint` and `break breakPoint` in Dubbo, pls. 
It would be better to replaced with lambda.

File: dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java [hunk 4]
```diff
@@ -175,10 +178,82 @@ private String getSpecifiedProtocol() {
...
+            Collection<ConsumerConfig> consumers = moduleModel.getConfigManager().getConsumers();
+            if (CollectionUtils.isNotEmpty(consumers)) {
+                for (ConsumerConfig config : consumers) {
+                    protocol = config.getProtocol();
+                    if (StringUtils.isNotEmpty(protocol)) {
+                        break breakPoint;
+                    }
+                }
+            }
+        }
```
Comment (AlbumenJ) [inline dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java:208]:
```suggestion
        protocol = moduleModels.stream()
                .map(ModuleModel::getConfigManager)
                .map(ModuleConfigManager::getConsumers)
                .filter(CollectionUtils::isNotEmpty)
                .flatMap(Collection::stream)
                .map(ConsumerConfig::getProtocol)
                .filter(StringUtils::isNotEmpty)
                .findFirst()
                .orElse(null);
```

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

File: dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java (hunk 4 above)
Comment (pandaapo) [reply dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java:208]: Thank you so much for your review! But it seems that the logic below can't be realized by lambda.
https://github.com/apache/dubbo/blob/33c2d1250194104dae4f446783926ef2429478e1/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java#L215-L230, now it is `ProtocolConfig` first `List<ProtocolConfig>` second in one `ProviderConfig`.
```
Stream<ProviderConfig> providerConfigStream = moduleModels.stream()
                .map(ModuleModel::getConfigManager)
                .map(ModuleConfigManager::getProviders)
                .filter(CollectionUtils::isNotEmpty)
                .flatMap(Collection::stream);
protocol = providerConfigStream
    .map(ProviderConfig::getProtocol)
    .filter((protocolConfig) -> protocolConfig != null)
    .map(ProtocolConfig::getName)
    .findFirst()
    .orElse("");
if (StringUtils.isEmpty(protocol)) {
    protocol = providerConfigStream
        .map(ProviderConfig::getProtocols)
        .filter(CollectionUtils::isNotEmpty)
        .flatMap(Collection::stream)
        .map(ProtocolConfig::getName)
        .filter(StringUtils::isNotEmpty)
        .findFirst()
        .orElse("");
}
```

After using lambda, it becomes `ProtocolConfig` in all `ProviderConfig` first, then `List<ProviderConfig>` in all `ProviderConfig`.
Do you have a better way to refactor this logic in lambda? Thank you.

Comment (pandaapo) [reply dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java]: Thank you for your review.

**Review by AlbumenJ — APPROVED** [review]
LGTM
