### PR TITLE
fix build string error

### LINKED ISSUE #12415: trile protocol config accesslog="true" lead to StackOverflowError
* Dubbo version: 3.1.5
* Operating System version: xxx
* Java version: jdk8

go client invoke java,Exception not print on java side,only go client side , AccessLogFilter convert request param (proto generated java class) to json,it lead to cycle invoke:
image

### PR DESCRIPTION
**Pull request by icodening**
## What is the purpose of the change
fix #12415

## Checklist
- [ ] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Review by AlbumenJ — CHANGES_REQUESTED** [review]
Please fix on 3.2

**Comment by icodening** [comment]
> Please fix on 3.2

OK

File: dubbo-common/src/main/java/org/apache/dubbo/common/utils/ToStringUtils.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+
+    private ToStringUtils() {
+    }
+
+    public static String printToString(Object obj) {
+        if (obj == null) {
+            return "null";
+        }
+        try {
+            return JsonUtils.getJson().toJson(obj);
```
Comment (AlbumenJ) [inline dubbo-common/src/main/java/org/apache/dubbo/common/utils/ToStringUtils.java:31]:
```suggestion
            return JsonUtils.toJson(obj);
```

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

**Review by AlbumenJ — APPROVED** [review]
