### PR TITLE
[master] Fix #8240, on branch master, when provider and consumer stop cause NPE

### LINKED ISSUE #8240: Dubbo provider and consumer  stop throw exception
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.12
* Operating System version: mac
* Java version: jdk1.8

### Steps to reproduce this issue

1. start dubbo provider
2. start dubbo consumer
3. stop dubbo consumer
4. stop dubbo provider

### Expected Result

not throw exception

### Actual Result

java.lang.IllegalStateException: There's no ApplicationConfig specified.
	at org.apache.dubbo.config.context.ConfigManager.lambda$getApplicationOrElseThrow$0(ConfigManager.java:89)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.apache.dubbo.config.context.ConfigManager.getApplicationOrElseThrow(ConfigManager.java:89)
	at org.apache.dubbo.rpc.model.ApplicationModel.getApplicationConfig(ApplicationModel.java:100)
	at org.apache.dubbo.rpc.model.ApplicationModel.getName(ApplicationModel.java:104)
	at org.apache.dubbo.rpc.model.ApplicationModel.getApplication(ApplicationModel.java:112)
	at org.apache.dubbo.registry.integration.RegistryProtocol.destroy(RegistryProtocol.java:575)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.destroy(ProtocolListenerWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.destroy(ProtocolFilterWrapper.java:88)
	at org.apache.dubbo.config.DubboShutdownHook.destroyProtocols(DubboShutdownHook.java:142)
	at org.apache.dubbo.config.DubboShutdownHook.destroyAll(DubboShutdownHook.java:129)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.destroy(DubboBootstrap.java:1276)
	at org.apache.dubbo.common.function.ThrowableAction.execute(ThrowableAction.java:46)
	at org.apache.dubbo.common.lang.ShutdownHookCallbacks.lambda$callback$0(ShutdownHookCallbacks.java:70)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.dubbo.common.lang.ShutdownHookCallbacks.callback(ShutdownHookCallbacks.java:70)
	at org.apache.dubbo.config.DubboShutdownHook.callback(DubboShutdownHook.java:85)
	at org.apache.dubbo.config.DubboShutdownHook.run(DubboShutdownHook.java:73)

reason：
1：service  stop first remove config
2：destroy protocol  find applicationConfig

### PR DESCRIPTION
**Pull request by wangchengming666**
issue #8240

这个bug可能是因为这个PR引起的：#7965

当执行`DubboBootstrap#destroy()`的时候，`clear()`方法清除了`ConfigManager`的缓存
https://github1s.com/apache/dubbo/blob/master/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java#L1273-L1274

然后`DubboShutdownHook.destroyAll();`中去销毁`protocol`的时候去拿了`ApplicationConfig`，因为上面已经在缓存中清除了，所以报了NPE。
https://github1s.com/apache/dubbo/blob/master/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java#L575-L576

另外`clear();`、`shutdown();`名字起的不是很好，我一并修改了。

### CODE REVIEW

File: dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java [hunk 1]
```diff
@@ -119,7 +119,7 @@ public static String tryGetApplication() {
             return application;
         }
         Optional<ApplicationConfig> appCfgOptional = getConfigManager().getApplication();
-        return appCfgOptional.isPresent() ? appCfgOptional.get().getName() : null;
+        return appCfgOptional.map(ApplicationConfig::getName).orElse(null);
```
Comment (DiegoKrupitza) [inline dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java:122]: Could be converted to a one liner. This will make it more readable and you do not really continue working with `appCfgOptional`.

My advice replace it with 

```
return getConfigManager().getApplication()
.map(ApplicationConfig::getName)
.orElse(null);
```

**Review by DiegoKrupitza — COMMENTED** [review]
The rest LGTM.

File: dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java (hunk 1 above)
Comment (wangchengming666) [reply dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java]: done

**Comment by BurningCN** [comment]
pls fix conflicts

**Comment by wangchengming666** [comment]
> pls fix conflicts

done. thanks
