### PR TITLE
[3.3] Optimized Wrapper#getWrapper and some unit tests

### LINKED ISSUE #15160: [Bug] Build and Test Scheduled On 3.3 might be always failed since 'feat: remove useless dependency(#15125)'
### Pre-check

- [x] I am sure that all the content I provide is in English.

### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo 3.x

### Steps to reproduce this issue

see ```Build and Test Scheduled On 3.3``` at https://github.com/apache/dubbo/actions

Almost all ```Unit Test On windows-latest``` are failed since feat: remove useless dependency(#15125), i doubt dubbo-test-check might not be removed from some test modules or ReplierDispatcherTest might have some issues about threadpool size.
```
Error:  Errors: 
Error:    ReplierDispatcherTest.testMultiThread:114 Execution org.opentest4j.AssertionFailedError
```
@Stellar1999  @CrazyHZM 

### What you expected to happen

Build and Test Scheduled On 3.3 should be successful.

### Anything else

_No response_

### Are you willing to submit a pull request to fix on your own?

- [x] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zrlw**
## What is the purpose of the change?
try to fix #15160
1. cached wrapper as soon as possible.
2. fixed exhausted thread pool issue: destroyed all framework model before running some unit tests. dubbo thread pool might be exhausted by some other unit tests which don't destroyed framework models after their running.
3. fixed address already in use issue: un-exported service config of some unit tests.

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Make sure gitHub actions can pass. [Why the workflow is failing and how to fix it?](../CONTRIBUTING.md)

### CODE REVIEW

**Comment by zrlw** [comment]
@AlbumenJ 
PTAL
i don't know this pr whether fixed the issue or not as```Build and Test Scheduled On 3.3``` could not be triggered on pull request.

**Comment by AlbumenJ** [comment]
> zrlw

You can trigger it on your own Github Repo Actions

**Comment by zrlw** [comment]
> > zrlw
> 
> You can trigger it on your own Github Repo Actions
i can trigger it but actions/checkout@v4 and other actions are not allowed to be used in my repository.
image

**Comment by zrlw** [comment]
> > > zrlw
> > 
> > 
> > You can trigger it on your own Github Repo Actions
> > i can trigger it but actions/checkout@v4 and other actions are not allowed to be used in my repository.
> > image

i got it
image

**Comment by zrlw** [comment]
i tested it on my own Github Repo Actions, 
1. it seemed that only adding back dubbo-test-check fixed #15160.
i doubt some dubbo-remoting-netty4 unit tests that runned before ReplierDispatcherTest don't destroy FrameworkModel, the issue was covered up because DubboTestChecker#executionFinished called FrameworkModel.destroyAll at the end of each test execution?

2. i found a new issue related with ``` EagerThreadPoolExecutorTest.testEagerThreadPoolFast```,  and it doesn't happen every time.
```
Error:  org.apache.dubbo.common.threadpool.support.eager.EagerThreadPoolExecutorTest.testEagerThreadPoolFast -- Time elapsed: 10.08 s <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition with Lambda expression in org.apache.dubbo.common.threadpool.support.eager.EagerThreadPoolExecutorTest was not fulfilled within 10 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:975)
	at org.apache.dubbo.common.threadpool.support.eager.EagerThreadPoolExecutorTest.testEagerThreadPoolFast(EagerThreadPoolExecutorTest.java:137)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```
see details https://github.com/zrlw/dubbo/actions/runs/13517737168/job/37770517010

File: dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java [hunk 1]
```diff
@@ -112,16 +112,17 @@ public Object invokeMethod(Object instance, String mn, Class<?>[] types, Object[
...
+            {
+                clazz = clazz.getSuperclass();
+            }
 
-        return ConcurrentHashMapUtils.computeIfAbsent(WRAPPER_MAP, c, Wrapper::makeWrapper);
+            if (clazz == Object.class) {
+                return OBJECT_WRAPPER;
+            }
+            return makeWrapper(clazz);
+        });
```
Comment (AlbumenJ) [inline dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java:125]: Why change this?

**Review by AlbumenJ — CHANGES_REQUESTED** [review]

File: dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java (hunk 1 above)
Comment (zrlw) [reply dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java:125]: > Why change this?

it desn't matter, i just thought dynamic class should not be checked every time for wrapping.
